1. 주어진 데이터는 각 소방서의 출동/도착 시간데이터이다.
출동시간과 도착시간 차이가 평균적으로 가장 오래 걸린 소방서의 시간을 분으로 변환해 출력하시오. (반올림 후 정수 출력)

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_1/data6-1-1.csv")
df["출동시간"] = pd.to_datetime(df["출동시간"])
df["도착시간"] = pd.to_datetime(df["도착시간"])

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df["차이"] = df["도착시간"] - df["출동시간"]
df["날짜"] = df["차이"].dt.total_seconds() / 60

In [ ]:
df["정수"] = df["차이"].astype("object")
df["정수"].max()
# 60+69+56
# 169분56초 ==> 170

119.93333333333334

2. 학교에서 교사 한 명당 맡은 학생 수가 가장 많은 학교를 찾고, 그 학교의 전체 교사 수를 구하시오. (정수 출력)

In [28]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_1/data6-1-2.csv")
df["합계"] = df["1학년"] + df["2학년"]+ df["3학년"]+df["4학년"]+df["5학년"]+df["6학년"]
df.head()

   학교명  교사수  1학년  2학년  3학년  4학년  5학년  6학년   합계
0  학교1   20  118   72  154  118   77   59  598
1  학교2   31  187  193  135  137   63   90  805
2  학교3   23  136  193  135  112   91   50  717
3  학교4   32   72  146   67   51  130  164  630
4  학교5   22   61   73   86   82   55  124  481

In [29]:
df["한명당"] = df["합계"] / df["교사수"]

In [45]:
df.head(8)
#19

   학교명  교사수  1학년  2학년  3학년  4학년  5학년  6학년    합계        한명당
0  학교1   20  118   72  154  118   77   59   598  29.900000
1  학교2   31  187  193  135  137   63   90   805  25.967742
2  학교3   23  136  193  135  112   91   50   717  31.173913
3  학교4   32   72  146   67   51  130  164   630  19.687500
4  학교5   22   61   73   86   82   55  124   481  21.863636
5  학교6   32  196  172  117  170   59  128   842  26.312500
6  학교7   29  183  173  102  184  194  130   966  33.310345
7  학교8   19  151  181  161  187  174  183  1037  54.578947

3. 연도별로 총 범죄 건수(범죄유형의 총합)의 월평균 값을 구한 후 그 값이 가장 큰 연도를 찾아, 해당 연도의 총 범죄 건수의 월평균 값을 출력하시오. (반올림하여 정수로 출력)

In [150]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_1/data6-1-3.csv")
df.head(10)

          날짜  강력범죄  절도범죄  폭력범죄  지능범죄  풍속범죄  교통범죄  경찰서명
0  2020년 04월    26   142    83    71    33   182  B경찰서
1  2021년 06월    12   131    78    65    30   201  E경찰서
2  2020년 06월    22   104    84    72    34   201  A경찰서
3  2024년 02월    16   137    72    80    30   180  C경찰서
4  2022년 03월    17   125    87    76    25   220  C경찰서
5  2024년 11월    25   148    90    67    33   210  B경찰서
6  2020년 07월    14   134    84    72    32   182  A경찰서
7  2020년 03월    14   129    76    60    29   202  C경찰서
8  2022년 01월    23   140    83    60    26   219  A경찰서
9  2022년 11월    26   122    72    62    31   180  E경찰서

In [165]:
ans = c/12

In [ ]:
# 515

514.9166666666666