# 작업형1
- 빅데이터 분석기사 3회 실기
- 데이터: members.csv 또는 임의 데이터 생성

## 문제1
- 결측치 데이터(행)을 제거하고, 앞에서부터 70% 데이터만 활용해, 'f1' 컬럼 1사분위 값을 구하시오
- 데이터: members.csv

In [59]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
print(df.shape)
df = df.dropna()
print(df.shape)

(100, 10)
(51, 10)

In [60]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

# print(df.isnull().sum())
# print(df.shape)
df = df.dropna()
# print(df.shape)

# print(int(len(df)*0.7))
df = df.iloc[:int(len(df)*0.7)]
# print(df.shape)

print(df['f1'].quantile(.25))

57.0

## 문제2
- index는 년도임. 2000년 데이터 중 2000년 평균보다 큰 값의 데이터 수
- 데이터: 아래 셀 실행

In [24]:
# 데이터 생성(먼저 실행해 주세요)
import pandas as pd
import random
random.seed(2022)
df = pd.DataFrame()
for i in range(0, 3):
    list_box = []
    for k in range(0, 200):
        ran_num = random.randint(1,200)
        list_box.append(ran_num)
    df[i+1999] = list_box
df = df.T
df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
1999,137,74,114,140,80,150,16,133,178,181,...,124,94,118,12,50,191,137,174,56,128
2000,176,87,64,110,128,16,8,4,123,87,...,59,22,3,108,17,104,101,161,156,43
2001,128,132,123,112,134,160,180,47,115,155,...,160,111,116,75,48,51,81,101,194,73

In [51]:
temp = df[2000]
temp
cond = temp > df[2000].mean()
df[cond][2000].count()

100

## 문제3
- 결측치가 제일 많은 값의 컬럼명
- 데이터: members.csv

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
df.info()
# f3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    object
 1   age         100 non-null    float64
 2   city        100 non-null    object
 3   f1          69 non-null     float64
 4   f2          100 non-null    int64
 5   f3          72 non-null     object
 6   f4          100 non-null    object
 7   f5          100 non-null    float64
 8   subscribed  100 non-null    object
 9   views       96 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.9+ KB

# 풀이

## 문제1
- 결측치 데이터(행)을 제거하고, 앞에서부터 70% 데이터만 활용해, 'f1' 컬럼 1사분위 값을 구하시오
- 데이터: members.csv

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

# print(df.isnull().sum())
# print(df.shape)
df = df.dropna()
# print(df.shape)

# print(int(len(df)*0.7))
df = df.iloc[:int(len(df)*0.7)]
# print(df.shape)

print(df['f1'].quantile(.25))

57.0

## 문제2
- index는 년도임. 2000년 데이터 중 2000년 평균보다 큰 값의 데이터 수
- 데이터: 아래 셀 실행

In [ ]:
# 데이터 생성(먼저 실행해 주세요)
import pandas as pd
import random
random.seed(2022)
df = pd.DataFrame()
for i in range(0, 3):
    list_box = []
    for k in range(0, 200):
        ran_num = random.randint(1,200)
        list_box.append(ran_num)
    df[i+1999] = list_box
df = df.T
df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
1999,137,74,114,140,80,150,16,133,178,181,...,124,94,118,12,50,191,137,174,56,128
2000,176,87,64,110,128,16,8,4,123,87,...,59,22,3,108,17,104,101,161,156,43
2001,128,132,123,112,134,160,180,47,115,155,...,160,111,116,75,48,51,81,101,194,73

In [ ]:
# 방법1
m = df.loc[2000].mean()
print(sum(df.loc[2000,:] > m))

# 방법2
df = df.T
m = df[2000].mean()
print(sum(df[2000] > m))

100
100

## 문제3
- 결측치가 제일 많은 값의 컬럼명
- 데이터: members.csv

In [ ]:
# 방법1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

df = df.isnull().sum()
df = df.sort_values(ascending=False)
print(df.index[0])

f1

In [ ]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

df = df.isnull().sum()
df = df.reset_index()
print(df.loc[3, 'index'])

f1