# 작업형1
- 빅데이터 분석기사 2회 실기 (참고: 1회 실기는 취소됨)
- 데이터: members.csv

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
df

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

      id    age city    f1  f2      f3    f4         f5  subscribed   views
0   id01    2.0   서울   NaN   0    gold  ENFJ  91.297791  2021-07-16  6820.0
1   id02    9.0   서울  70.0   1     NaN  ENFJ  60.339826  2021-05-12  2534.0
2   id03   27.0   서울  61.0   1    gold  ISTJ  17.252986  2021-03-16  7312.0
3   id04   75.0   서울   NaN   2     NaN  INFP  52.667078  2021-07-21   493.0
4   id05   24.0   서울  85.0   2     NaN  ISFJ  29.269869  2021-03-07  1338.0
..   ...    ...  ...   ...  ..     ...   ...        ...         ...     ...
95  id95   77.0   경기  43.0   1    gold  INTJ  91.297791  2021-05-21  8697.0
96  id96   92.0   경기  53.0   1  silver  ENTJ  52.667078  2021-05-06  4336.0
97  id97  100.0   경기   NaN   0    gold  INFP  67.886373  2021-03-18  6687.0
98  id98   39.0   경기  58.0   2     NaN  INFP  98.429899  2021-10-02   865.0
99  id99    1.0   경기  47.0   0    gold  ESFJ  97.381034  2021-12-02  6090.0

[100 rows x 10 columns]

## 문제1
- 주어진 데이터셋(members.csv)에서 'views' 컬럼을 기준으로 내림차순 정렬하고, 'views'컬럼 상위 10개 데이터를 상위 10번째 값으로 대체한 후 'age'컬럼에서 80 이상인 데이터의 'views' 컬럼 평균값 구하시오

In [20]:
# your code
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
df = df.sort_values(by="views",ascending = False)
df = df.reset_index(drop=True)
tmp = df.iloc[9]["views"]
df.loc[0:9,"views"] = tmp

In [27]:
temp = df.loc[0:9]
temp
cond = temp["age"] >= 80
ans = temp[cond]["views"].sum() // 3
ans

9690.0

## 문제2
- 주어진 데이터셋(members.csv)의 앞에서부터 순서대로 80% 데이터만 활용해 'f1'컬럼 결측치를 중앙값으로 채우기 전 후의 표준편차를 구하고, 두 표준편차 차이 계산하기
(단, 표본표준편차 기준, 두 표준편차 차이는 절대값으로 계산)

In [34]:
# your code
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
df
temp = df.loc[0:79]
std_prev = temp["f1"].std()
temp = temp.fillna(temp['f1'].mean())
std_next = temp["f1"].std()

ans = (std_prev - std_next)
ans

3.564235665191312

## 문제3
- 주어진 데이터셋(members.csv)의 'age'컬럼의 이상치를 모두 더하시오!
- 단, 평균으로부터 '표준편차*1.5'를 벗어나는 영역을 이상치라고 판단함

In [53]:
# your code
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
a = df["age"].quantile(0.25)
b = df["age"].quantile(0.75)
IQR = b-a
cond1 = ((a - 1.5*IQR) > df["age"])
cond2 = ((b + 1.5*IQR) < df["age"])

df[cond1|cond2]["age"].sum()
# 1. 계산된 하한선과 상한선 확인해보기
print("하한선:", a - 1.5*IQR)
print("상한선:", b + 1.5*IQR)
# 2. 데이터의 최소/최대 나이 확인해보기 (하한/상한을 안 벗어나는지 확인)
print("최소 나이:", df["age"].min())
print("최대 나이:", df["age"].max())
# 3. 이상치 개수 확인해보기 (0이 나오면 이상치가 없다는 뜻!)
print("이상치 개수:", len(df[cond1|cond2]))
# 4. 최종 합계 출력
print("이상치 나이의 합:", df[cond1|cond2]["age"].sum())

하한선: -48.3125
상한선: 152.1875
최소 나이: -13.5
최대 나이: 100.0
이상치 개수: 0
이상치 나이의 합: 0.0

# 풀이

## 문제1
- 주어진 데이터셋(members.csv)의 'views' 컬럼 상위 10개 데이터를 상위 10번째 값으로 대체한 후 'age'컬럼에서 80 이상인 데이터의 'views' 컬럼 평균값 구하기

풀이 순서
- views 컬럼 - 내림차순 정렬 - 상위 10개 불러오기
- 10개 중에서 10번째 (최소값) 값 확인 후 대체
- age가 80 이상의 views 컬럼 평균

In [ ]:
# views 컬럼 - 내림차순 정렬 - 상위 10개 불러오기
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")
df = df.sort_values('views', ascending=False)
df.head(10)

       id   age city    f1  f2    f3    f4         f5  subscribed    views
5    id06  22.0   서울  57.0   0   vip  INTP  20.129444  2021-09-12  21550.0
56   id56  59.0   대구   NaN   1   vip  ESTJ  73.586397  2021-04-05  19589.0
83   id83  73.0   경기  50.0   1   vip  ENTP  80.138280  2021-09-26  19139.0
32   id32  25.0   부산  64.0   0   vip  ISFJ  13.049921  2021-05-24  17421.0
10  id100  47.0   경기  53.0   0   vip  ESFP  33.308999  2021-02-21  15535.0
9    id10  95.0   서울  74.0   1  gold  ISFP  98.429899  2021-04-03   9992.0
49   id49  75.0   대구  88.0   0  gold  INTP  37.113739  2021-03-31   9737.0
36   id36  68.0   부산  77.0   1  gold  INTP  13.049921  2021-07-20   9713.0
46   id46  93.0   대구   NaN   0  gold  ESTJ  67.886373  2021-05-23   9711.0
21   id21  90.0   부산   NaN   1  gold  ISFP  29.269869  2021-05-03   9690.0

In [ ]:
#10개 중에서 10번째 (최소값) 값 확인 / index는 0부터 시작
min_value = df['views'][:10].min()
print(min_value)

# min_value = df['views'].iloc[9]
# print(min_value)
# min_value = df['views'].head(10).min()
# print(min_value)

9690.0

In [ ]:
#10개 중에서 10번째 (최소값) 값 대체
df.iloc[:10,-1] = min_value

In [ ]:
# 대체된 데이터 확인
df.head(12)

       id   age city    f1  f2    f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0   vip  INTP  20.129444  2021-09-12  9690.0
56   id56  59.0   대구   NaN   1   vip  ESTJ  73.586397  2021-04-05  9690.0
83   id83  73.0   경기  50.0   1   vip  ENTP  80.138280  2021-09-26  9690.0
32   id32  25.0   부산  64.0   0   vip  ISFJ  13.049921  2021-05-24  9690.0
10  id100  47.0   경기  53.0   0   vip  ESFP  33.308999  2021-02-21  9690.0
9    id10  95.0   서울  74.0   1  gold  ISFP  98.429899  2021-04-03  9690.0
49   id49  75.0   대구  88.0   0  gold  INTP  37.113739  2021-03-31  9690.0
36   id36  68.0   부산  77.0   1  gold  INTP  13.049921  2021-07-20  9690.0
46   id46  93.0   대구   NaN   0  gold  ESTJ  67.886373  2021-05-23  9690.0
21   id21  90.0   부산   NaN   1  gold  ISFP  29.269869  2021-05-03  9690.0
92   id92  97.0   경기  78.0   1  gold  INFP  97.381034  2021-05-08  9625.0
16   id16  68.0   서울  85.0   0  gold  ESFP  16.283854  2021-07-25  9472.0

In [ ]:
# age가 80 이상의 views 컬럼 평균
cond = df['age']>=80
print(df[cond]['views'].mean())

5674.04347826087

## 문제2
- 주어진 데이터셋(members.csv)의 앞에서부터 순서대로 80% 데이터만 활용해 'f1'컬럼 결측치를 중앙값으로 채우기 전 후의 표준편차를 구하고, 두 표준편차 차이 계산하기
(단, 표본표준편차 기준, 두 표준편차 차이는 절대값으로 계산)

풀이 순서
- 앞에서 부터 80% 데이터 뽑아오기
- f1 컬럼 표준편차 구하기
- f1 컬럼 결측치, 중앙값 확인
- f1 컬럼 결측값 중앙값으로 채우기
- f1 컬럼 표준편차 구하기
- 두 표준편차 차이 계산

In [ ]:
# 앞에서 부터 80% 데이터 뽑아오기
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

line = int(len(df) * 0.8)
line
df = df.iloc[:line] # 0~79
df

      id   age city    f1  f2    f3    f4         f5  subscribed   views
0   id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2021-07-16  6820.0
1   id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2021-05-12  2534.0
2   id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2021-03-16  7312.0
3   id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2021-07-21   493.0
4   id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2021-03-07  1338.0
..   ...   ...  ...   ...  ..   ...   ...        ...         ...     ...
75  id75  63.0   경기  47.0   0  gold  ESTP  20.129444  2021-06-12  6779.0
76  id76  71.0   경기  12.0   0   NaN  ENTJ  83.685380  2021-07-28  2872.0
77  id77  77.0   경기  31.0   0   NaN  INFP  98.429899  2021-01-16  1518.0
78  id78  92.0   경기  96.0   1  gold  INTJ  69.730313  2021-10-27  7565.0
79  id79  30.0   경기   NaN   0  gold  INTJ  80.138280  2021-08-14  8777.0

[80 rows x 10 columns]

In [ ]:
## 결측치 채우기 전 f1컬럼 표준편자
std1 = df['f1'].std()
std1

20.574853076621935

In [ ]:
## 결측치 확인
df.isnull().sum()

id             0
age            0
city           0
f1            25
f2             0
f3            22
f4             0
f5             0
subscribed     0
views          3
dtype: int64

In [ ]:
## 중앙값 확인
med=df['f1'].median()
med

68.0

In [ ]:
## 중앙값으로 채우기
df['f1'] = df['f1'].fillna(med)

In [ ]:
## 결측치 확인
df.isnull().sum()

id             0
age            0
city           0
f1             0
f2             0
f3            22
f4             0
f5             0
subscribed     0
views          3
dtype: int64

In [ ]:
## 결측치를 채운 후 표준편차 구하기
std2 = df['f1'].std()
std2

17.010788646613268

In [ ]:
# 두 표준편차 차이 계산
print(abs(std1-std2))

3.564064430008667

### 심화학습
- 모 표준편차(넘파이) vs 표본 표준편차(판다스)

In [ ]:
# import numpy as np
# print(df['f1'].std())
# print(np.std(df['f1']))

## 문제3
- 주어진 데이터셋(members.csv)의 'age'컬럼의 이상치를 모두 더하시오!
- 단, 평균으로부터 '표준편차*1.5'를 벗어나는 영역을 이상치라고 판단함

풀이 순서
- 표준편차, 평균값 구하기
- 이상치 최저, 최고 기준 구하기
- 이상치를 벗어나는 값(조건) 찾아 더하기

In [ ]:
# 표준편차, 평균값 구하기
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/members.csv")

std = df['age'].std() * 1.5
mean = df['age'].mean()

print("표준편차 * 1.5 : ", std)
print("평균 : ", mean)

표준편차 * 1.5 :  45.66413778388304
평균 :  50.963

In [ ]:
# 이상치 최저, 최고 기준 구하기
lower = mean - std
upper = mean + std

print("이상치 최저 기준 : ", lower)
print("이상치 최고 기준 : ", upper)

이상치 최저 기준 :  5.298862216116959
이상치 최고 기준 :  96.62713778388304

In [ ]:
# 이상치를 벗어나는 값(조건) 찾기

cond1 = df['age'] < lower
cond2 = df['age'] > upper

df[cond1]

      id   age city     f1  f2      f3    f4         f5  subscribed   views
0   id01   2.0   서울    NaN   0    gold  ENFJ  91.297791  2021-07-16  6820.0
8   id09   3.3   서울   35.0   2     NaN  ESFJ  17.252986  2021-03-21  2764.0
22  id22  -6.3   부산   72.0   1    gold  ENFP  52.667078  2021-02-09  6147.0
29  id29 -13.5   부산   47.0   2    gold  ENTP  67.886373  2021-08-28  6793.0
57  id57   3.0   대구  111.0   0  silver  ISFJ  29.269869  2021-01-12  4421.0
58  id58   0.0   대구  100.0   2     NaN  ESTP  33.308999  2021-04-18  1928.0
70  id70  -9.0   경기   96.0   1  silver  ISTP  48.431184  2021-11-17  4442.0
86  id86   2.0   경기    NaN   0     NaN  ESTP  29.269869  2021-02-16  2155.0
99  id99   1.0   경기   47.0   0    gold  ESFJ  97.381034  2021-12-02  6090.0

In [ ]:
df[cond2]

      id    age city    f1  f2      f3    f4         f5  subscribed   views
37  id37  100.0   부산   NaN   0  silver  ESTP  33.308999  2021-07-08  4068.0
45  id45   97.0   대구  88.0   0    gold  ENFJ  13.049921  2021-06-21  8317.0
52  id52   97.0   대구  82.0   1    gold  ISFJ  90.496999  2021-05-20  8518.0
92  id92   97.0   경기  78.0   1    gold  INFP  97.381034  2021-05-08  9625.0
97  id97  100.0   경기   NaN   0    gold  INFP  67.886373  2021-03-18  6687.0

In [ ]:
# 이상치 age합
print(df[cond1|cond2]['age'].sum())

473.5