In [1]:
# 데이터
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p3/order.csv")
df.head()

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

   할인율  온도  광고비  주문량
0   28  15  342  635
1   24  34  666  958
2   13  15  224  525
3    0  22  764   25
4   27  29  148  607

In [2]:
df.corr()

          할인율        온도       광고비       주문량
할인율  1.000000  0.093928 -0.228091  0.101179
온도   0.093928  1.000000  0.012635  0.377303
광고비 -0.228091  0.012635  1.000000  0.478948
주문량  0.101179  0.377303  0.478948  1.000000

In [7]:
from statsmodels.formula.api import ols
model = ols("주문량 ~ 할인율 + 온도 + 광고비",df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    주문량   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     5.770
Date:                Thu, 11 Jun 2026   Prob (F-statistic):            0.00366
Time:                        19:01:01   Log-Likelihood:                -194.11
No. Observations:                  30   AIC:                             396.2
Df Residuals:                      26   BIC:                             401.8
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    267.6609    129.985      2.059      0.050       0.472     534.849
할인율            4.2068      3.549      1.185      0.247      -3.089      11.503
온도             9.4798      4.098      2.313      0.029       1.057      17.903
광고비            0.4148      0.125      3.310      0.003       0.157       0.672
==============================================================================
Omnibus:                       56.788   Durbin-Watson:                   1.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              419.005
Skew:                          -3.845   Prob(JB):                     1.03e-91
Kurtosis:                      19.616   Cond. No.                     2.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
new_data = pd.DataFrame({"할인율": [15], "온도": [25], "광고비": [300]})
a = model.get_prediction(new_data)

help(a.summary_frame)
print(a.summary_frame(0.1))

Help on method summary_frame in module statsmodels.regression._prediction:

summary_frame(alpha=0.05) method of statsmodels.regression._prediction.PredictionResults instance

         mean    mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  692.207386  45.555397     614.507283     769.907488    395.622293

   obs_ci_upper
0    988.792478

In [15]:
mse = (df["잔차"]**2).mean()
mse

24406.596627140243

In [ ]:
# 다중 선형 회귀 모델 적합
from statsmodels.formula.api import ols
model = ols('주문량 ~ 할인율 + 온도 + 광고비', data=df).fit()

# 1. 상관계수
print("1. 상관계수:", round(df['할인율'].corr(df['온도']), 2))

# 2. 결정계수
print("2. 결정계수(R-squared):", round(model.rsquared, 2))

# 3. 회귀계수(기울기)
print("3. 회귀계수:", round(model.params, 4))

# 4. 절편
print("4. 절편:", round(model.params['Intercept'], 4))

# 5. 회귀계수 검정
print("5. pvalue:", round(model.pvalues['온도'], 4))

# 6. 예측 판매량
new_data = pd.DataFrame({"할인율": [10], "온도": [20], "광고비": [500]})
result = model.predict(new_data)
print("6. 새로운 데이터:", int(result[0]))

# 7. 잔차 제곱합
df['잔차'] = df['주문량'] - model.predict(df)
print("7. 잔차 제곱합:", round(sum(df['잔차']**2), 2))

# 8. MSE(Mean Squared Error)
MSE = (df['잔차'] ** 2).mean()
print('8. MSE:', round(MSE, 4))

# 9. 각 변수에 대한 90% 신뢰구간
print("9. 신뢰구간:\n", model.conf_int(alpha=0.1))

# 10. 새로운 데이터의 예측값의 90% 신뢰구간과 예측구간
new_data = pd.DataFrame({"할인율": [15], "온도": [25], "광고비": [300]})
pred = model.get_prediction(new_data)
result = pred.summary_frame(alpha=0.1)
print("10. 예측값의 신뢰구간과 예측구간:\n", result)

# 11. 광고비는 배달 주문량에 영향을 주는지 가설 검정
cond = model.pvalues['광고비'] < 0.05
if cond:
    result = "기각"
else:
    result = "채택"
print("11. 귀무가설", result)

# 선형 회귀 모델의 요약 결과
print(model.summary())

1. 상관계수: 0.09
2. 결정계수(R-squared): 0.4
3. 회귀계수: Intercept    267.6609
할인율            4.2068
온도             9.4798
광고비            0.4148
dtype: float64
4. 절편: 267.6609
5. pvalue: 0.0289
6. 새로운 데이터: 706
7. 잔차 제곱합: 732197.9
8. MSE: 24406.5966
9. 신뢰구간:
                    0           1
Intercept  45.955720  489.366084
할인율        -1.847229   10.260887
온도          2.490702   16.468984
광고비         0.201064    0.628589
10. 예측값의 신뢰구간과 예측구간:
          mean    mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  692.207386  45.555397     614.507283     769.907488    395.622293

   obs_ci_upper
0    988.792478
11. 귀무가설 기각
                            OLS Regression Results
==============================================================================
Dep. Variable:                    주문량   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     5.770
Date:                Sun, 16 Nov 2025   Prob (F-statistic):            0.00366
Time:                        06:48:42   Log-Likelihood:                -194.11
No. Observations:                  30   AIC:                             396.2
Df Residuals:                      26   BIC:                             401.8
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    267.6609    129.985      2.059      0.050       0.472     534.849
할인율            4.2068      3.549      1.185      0.247      -3.089      11.503
온도             9.4798      4.098      2.313      0.029       1.057      17.903
광고비            0.4148      0.125      3.310      0.003       0.157       0.672
==============================================================================
Omnibus:                       56.788   Durbin-Watson:                   1.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              419.005
Skew:                          -3.845   Prob(JB):                     1.03e-91
Kurtosis:                      19.616   Cond. No.                     2.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.