In [174]:
import pandas as pd
# Series도 표로 렌더링되게 만들기
pd.Series._repr_html_ = lambda self: self.to_frame()._repr_html_()

In [175]:
menu = pd.Series(['비빔밥','김치찌개','된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [176]:
price = pd.Series([10000,9000,8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [177]:
# 데이터 프레임으로 만들기
df = pd.DataFrame({
    '메뉴' : menu,
    '가격' : price
})
df

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [178]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [179]:
cols = ['메뉴','가격']
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [180]:
# 데이터 준비하기
df = pd.DataFrame({
    "메뉴" : ["아메리카노","카페라떼","카페모카","카푸치노","에스프레소","밀크티","녹차"],
    "가격" : [4500,5000,5500,5000,4000,5900,5300],
    "칼로리" : [10,110,250,110,20,210,0]
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [181]:
df.to_csv('cafe.csv', index=False)

In [182]:
df = pd.read_csv('cafe.csv')

In [183]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [184]:
# 앞에서부터 2개
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [185]:
# 뒤에서부터 3개
df.tail(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [186]:
# 랜덤하게 3개
df.sample(3)

      메뉴    가격  칼로리
1   카페라떼  5000  110
0  아메리카노  4500   10
6     녹차  5300    0

In [187]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [188]:
df.shape

(7, 3)

In [189]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes

In [190]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [191]:
# 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car" : ["Sedan","SUV","Sedan","SUV","SUV","SUV","Sedan","Sedan","Sedan","Sedan","Sedan"],
    "size" : ["S","M","S","S","M","M","L","S","S","M","S"]
})

In [192]:
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [193]:
# 항목 종류 수
df_car.nunique()

car     2
size    3
dtype: int64

In [194]:
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [195]:
print(df_car['car'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [196]:
# 숫자형 데이터만 보여줌
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [197]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [198]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [199]:
import pandas as pd
# 데이터 준비
data = {
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리":['10', '110', '250', '110', '20', '210', '0'],
}

In [200]:
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 296.0+ bytes

In [201]:
df

      메뉴      가격  칼로리
0  아메리카노  4500.0   10
1   카페라떼  5000.0  110
2   카페모카  5500.0  250
3   카푸치노  5000.0  110
4  에스프레소  4000.0   20
5    밀크티  5900.0  210
6     녹차  5300.0    0

In [202]:
df['가격'] = df['가격'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int32
 2   칼로리     7 non-null      object
dtypes: int32(1), object(2)
memory usage: 268.0+ bytes

In [203]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [204]:
# 자료형 변환 / astype / object -> float
df['칼로리'] = df['칼로리'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int32
 2   칼로리     7 non-null      int32
dtypes: int32(2), object(1)
memory usage: 240.0+ bytes

In [205]:
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [206]:
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [207]:
# 할인가 컬럼 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [208]:
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [209]:
# axis = 0 행을선택해서 첫번쨰 행삭제
df = df.drop(1,axis=0)
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [210]:
df = df.drop('칼로리', axis = 1)
df

      메뉴    가격  new     할인가
0  아메리카노  4500    0  3600.0
2   카페모카  5500    0  4400.0
3   카푸치노  5000    0  4000.0
4  에스프레소  4000    0  3200.0
5    밀크티  5900    0  4720.0
6     녹차  5300    0  4240.0

In [211]:
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [212]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [213]:
df.loc[1,'가격']

5000

In [214]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [215]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [216]:
df.loc[1:3,['메뉴','칼로리']]

     메뉴  칼로리
1  카페라떼  110
2  카페모카  250
3  카푸치노  110

In [217]:
## iloc (인덱스 번호로 지정)
df = pd.read_csv('cafe.csv')
df = df.drop(0,axis=0)

In [218]:
df

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [219]:
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [220]:
df.iloc[:,1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [221]:
df.iloc[2,0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [222]:
df.loc[2:3,'메뉴':'칼로리']

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [223]:
import pandas as pd

In [224]:
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [225]:
import numpy as np
df['원산지'] = np.nan
df

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN
4  에스프레소  4000   20  NaN
5    밀크티  5900  210  NaN
6     녹차  5300    0  NaN

In [226]:
df.loc[0,"원산지"] = "콜롬비아"

C:\Users\dnwpg\AppData\Local\Temp\ipykernel_27332\1199474516.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0,"원산지"] = "콜롬비아"

In [227]:
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250   NaN
3   카푸치노  5000  110   NaN
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN

In [228]:
df.loc['시즌'] = {'메뉴' : '딴짓커피','가격':2000,'칼로리':10}

In [229]:
df

       메뉴    가격  칼로리   원산지
0   아메리카노  4500   10  콜롬비아
1    카페라떼  5000  110   NaN
2    카페모카  5500  250   NaN
3    카푸치노  5000  110   NaN
4   에스프레소  4000   20   NaN
5     밀크티  5900  210   NaN
6      녹차  5300    0   NaN
시즌   딴짓커피  2000   10   NaN

In [230]:
# 리스트 형태로 데이터(행) 추가
df.loc[7] = ['크리스마스라떼',6000,300,'한국']
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250   NaN
3      카푸치노  5000  110   NaN
4     에스프레소  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌     딴짓커피  2000   10   NaN
7   크리스마스라떼  6000  300    한국

In [231]:
df = df.drop("시즌",axis = 0)
df.to_csv("cafe2.csv", index=False)

In [232]:
df = pd.read_csv('cafe2.csv')
df

        메뉴    가격  칼로리   원산지
0    아메리카노  4500   10  콜롬비아
1     카페라떼  5000  110   NaN
2     카페모카  5500  250   NaN
3     카푸치노  5000  110   NaN
4    에스프레소  4000   20   NaN
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN
7  크리스마스라떼  6000  300    한국

In [233]:
# 인덱스 기준(False 내림차순)
df.sort_index(ascending=False)

        메뉴    가격  칼로리   원산지
7  크리스마스라떼  6000  300    한국
6       녹차  5300    0   NaN
5      밀크티  5900  210   NaN
4    에스프레소  4000   20   NaN
3     카푸치노  5000  110   NaN
2     카페모카  5500  250   NaN
1     카페라떼  5000  110   NaN
0    아메리카노  4500   10  콜롬비아

In [234]:
# 메뉴 기준(False 내림차순)
df.sort_values("메뉴",ascending=False)

        메뉴    가격  칼로리   원산지
7  크리스마스라떼  6000  300    한국
3     카푸치노  5000  110   NaN
2     카페모카  5500  250   NaN
1     카페라떼  5000  110   NaN
4    에스프레소  4000   20   NaN
0    아메리카노  4500   10  콜롬비아
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN

In [235]:
df = df.sort_values(['가격','메뉴'], ascending = [False,True])
df

        메뉴    가격  칼로리   원산지
7  크리스마스라떼  6000  300    한국
5      밀크티  5900  210   NaN
2     카페모카  5500  250   NaN
6       녹차  5300    0   NaN
1     카페라떼  5000  110   NaN
3     카푸치노  5000  110   NaN
0    아메리카노  4500   10  콜롬비아
4    에스프레소  4000   20   NaN

In [236]:
df.reset_index(drop=True)

        메뉴    가격  칼로리   원산지
0  크리스마스라떼  6000  300    한국
1      밀크티  5900  210   NaN
2     카페모카  5500  250   NaN
3       녹차  5300    0   NaN
4     카페라떼  5000  110   NaN
5     카푸치노  5000  110   NaN
6    아메리카노  4500   10  콜롬비아
7    에스프레소  4000   20   NaN

In [237]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [238]:
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7    False
Name: 칼로리, dtype: bool

In [239]:
cond = df['칼로리'] < 50
df[cond]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN

In [240]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df

        메뉴    가격  칼로리   원산지
0    아메리카노  4500   10  콜롬비아
1     카페라떼  5000  110   NaN
2     카페모카  5500  250   NaN
3     카푸치노  5000  110   NaN
4    에스프레소  4000   20   NaN
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN
7  크리스마스라떼  6000  300    한국

In [241]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False  False   True
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False  False

In [242]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    6
dtype: int64

In [243]:
df

        메뉴    가격  칼로리   원산지
0    아메리카노  4500   10  콜롬비아
1     카페라떼  5000  110   NaN
2     카페모카  5500  250   NaN
3     카푸치노  5000  110   NaN
4    에스프레소  4000   20   NaN
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN
7  크리스마스라떼  6000  300    한국

In [244]:
df['원산지'] = df['원산지'].fillna('코스타리카')
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [245]:
df.to_csv('cafe3.csv',index=False)

In [246]:
df = pd.read_csv('cafe3.csv')
df.head()

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250  코스타리카
3   카푸치노  5000  110  코스타리카
4  에스프레소  4000   20  코스타리카

In [247]:
df = df.replace('아메리카노', "룽고")
df = df.replace('녹차','그린티')
df

        메뉴    가격  칼로리    원산지
0       룽고  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6      그린티  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [248]:
change = {'룽고':'아메리카노','그린티':"녹차"}
df = df.replace(change)

In [249]:
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [250]:
df.loc[6,"원산지"] = "대한민국"
df.loc[6]

메뉴       녹차
가격     5300
칼로리       0
원산지    대한민국
Name: 6, dtype: object

In [251]:
df.to_csv('cafe4.csv',index=False)

In [252]:
import pandas as pd
df = pd.DataFrame({"만족도" : ["만족","보통","불만","만족"]})

mapping = {"만족" : 3, "보통": 2, "불만" : 1}
df['만족도조사'] = df['만족도'].map(mapping)
df

  만족도  만족도조사
0  만족      3
1  보통      2
2  불만      1
3  만족      3

In [253]:
import pandas as pd
df = pd.DataFrame({"A":['데이터 분석','기본 학습서','퇴근 후 열공'],
                   "B":[10,20,30],
                   "C":['ab cd','AB CD','ab cd ']
                   })
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [254]:
df['A'] = df['A'].replace("분석","시각화")
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [255]:
df['A'] = df['A'].str.replace("분석","시각화")
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [256]:
# 에러
# df['B'] = df['B'].str.replace(10,20)
# df

In [257]:
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [258]:
df['D'] = df['A'].str.split().str[0]
df

         A   B       C    D
0  데이터 시각화  10   ab cd  데이터
1   기본 학습서  20   AB CD   기본
2  퇴근 후 열공  30  ab cd    퇴근

In [259]:
# 이걸 통해 검색
df["A"].str.contains("기본")

0    False
1     True
2    False
Name: A, dtype: bool

In [260]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A   B       C    D  기본포함유무
0  데이터 시각화  10   ab cd  데이터   False
1   기본 학습서  20   AB CD   기본    True
2  퇴근 후 열공  30  ab cd    퇴근   False

In [261]:
# 단어의 일부로는 못찾음
menu = pd.Series(['맛난버거 세트','매운 치킨버거','더블 치즈버거'])
menu.isin(['맛난버거 세트','더블 치즈버거'])

0     True
1    False
2     True
dtype: bool

In [262]:
menu.str.contains('세트')

0     True
1    False
2    False
dtype: bool

In [263]:
df

         A   B       C    D  기본포함유무
0  데이터 시각화  10   ab cd  데이터   False
1   기본 학습서  20   AB CD   기본    True
2  퇴근 후 열공  30  ab cd    퇴근   False

In [264]:
df["C"].str[1:3]

0    b
1    B
2    b
Name: C, dtype: object

In [265]:
df["C"][1:3]

1     AB CD
2    ab cd
Name: C, dtype: object

In [266]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카

In [267]:
print(len(df))
print(df.shape[0])

8
8

In [268]:
cond = df['가격'] > 5000

print(sum(cond))

print(len(df[cond]))

4
4

In [269]:
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0   대한민국
7  크리스마스라떼  6000  300     한국

In [270]:
# 열 별 합계
df.sum(numeric_only=True)

가격     41200
칼로리     1010
dtype: int64

In [271]:
df.sum(axis = 1, numeric_only=True)

0    4510
1    5110
2    5750
3    5110
4    4020
5    6110
6    5300
7    6300
dtype: int64

In [272]:
df.sum(axis = 0, numeric_only=True)

가격     41200
칼로리     1010
dtype: int64

In [273]:
print("최대값: ",df['가격'].max())
print("최소값: ",df['가격'].min())
print("평균값: ",df['가격'].mean())
print("중앙값: ",df['가격'].median())
print("합계: ",df['가격'].sum())
print("표준편차: ",df['가격'].std())
print("분산: ",df['가격'].var())

최대값:  6000
최소값:  4000
평균값:  5150.0
중앙값:  5150.0
합계:  41200
표준편차:  678.2329983125268
분산:  460000.0

In [274]:
## 1사분위
df['가격'].quantile(.25)

4875.0

In [275]:
## 3사분위
df['가격'].quantile(.75)

5600.0

In [276]:
# 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
4  에스프레소  4000   20  코스타리카

In [277]:
df['원산지'].mode()

0    코스타리카
Name: 원산지, dtype: object

In [278]:
df['가격'].idxmax()

7

In [279]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

메뉴     크리스마스라떼
가격        6000
칼로리        300
원산지         한국
Name: 7, dtype: object

In [280]:
df.nlargest(3,"가격")

        메뉴    가격  칼로리    원산지
7  크리스마스라떼  6000  300     한국
5      밀크티  5900  210  코스타리카
2     카페모카  5500  250  코스타리카

In [281]:
df.nsmallest(3,"가격")

      메뉴    가격  칼로리    원산지
4  에스프레소  4000   20  코스타리카
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카

In [282]:
# apply 적용해서 새로운 컬럼 적용하기
def cal(x):
    if x >= 100:
        return "No"
    else:
        return "Yes"
    
df['먹어도될까요'] = df["칼로리"].apply(cal)
df

        메뉴    가격  칼로리    원산지 먹어도될까요
0    아메리카노  4500   10   콜롬비아    Yes
1     카페라떼  5000  110  코스타리카     No
2     카페모카  5500  250  코스타리카     No
3     카푸치노  5000  110  코스타리카     No
4    에스프레소  4000   20  코스타리카    Yes
5      밀크티  5900  210  코스타리카     No
6       녹차  5300    0   대한민국    Yes
7  크리스마스라떼  6000  300     한국     No

In [283]:
import pandas as pd

df = pd.DataFrame({
    'Name': {0: '쿼카', 1: '알파카', 2: '시바견'},
    '수학': {0: 90, 1: 93, 2: 85},
    '영어': {0: 92, 1: 84, 2: 86},
    '국어': {0: 91, 1: 94, 2: 83},
})

df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [284]:
import pandas as pd
df = pd.read_csv("cafe4.csv")
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0   대한민국
7  크리스마스라떼  6000  300     한국

In [285]:
df.groupby(['원산지']).mean(numeric_only=True)

           가격    칼로리
원산지
대한민국   5300.0    0.0
코스타리카  5080.0  140.0
콜롬비아   4500.0   10.0
한국     6000.0  300.0

In [286]:
# 원산지와 칼로리 기준, 평균
df.groupby(['원산지','칼로리']).mean(numeric_only=True)

               가격
원산지   칼로리
대한민국  0    5300.0
코스타리카 20   4000.0
      110  5000.0
      210  5900.0
      250  5500.0
콜롬비아  10   4500.0
한국    300  6000.0

In [287]:
# 원산지와 메뉴 기준(평균,합계)
df.groupby(["원산지","메뉴"]).agg(["mean","sum"])

                   가격          칼로리
                 mean   sum   mean  sum
원산지   메뉴
대한민국  녹차       5300.0  5300    0.0    0
코스타리카 밀크티      5900.0  5900  210.0  210
      에스프레소    4000.0  4000   20.0   20
      카페라떼     5000.0  5000  110.0  110
      카페모카     5500.0  5500  250.0  250
      카푸치노     5000.0  5000  110.0  110
콜롬비아  아메리카노    4500.0  4500   10.0   10
한국    크리스마스라떼  6000.0  6000  300.0  300

In [288]:
# 원산지와 메뉴 기준(평균,합계)
df.groupby(["원산지","메뉴"]).agg(["mean","sum"]).reset_index()

     원산지       메뉴      가격          칼로리
                     mean   sum   mean  sum
0   대한민국       녹차  5300.0  5300    0.0    0
1  코스타리카      밀크티  5900.0  5900  210.0  210
2  코스타리카    에스프레소  4000.0  4000   20.0   20
3  코스타리카     카페라떼  5000.0  5000  110.0  110
4  코스타리카     카페모카  5500.0  5500  250.0  250
5  코스타리카     카푸치노  5000.0  5000  110.0  110
6   콜롬비아    아메리카노  4500.0  4500   10.0   10
7     한국  크리스마스라떼  6000.0  6000  300.0  300

In [289]:
# transform
import pandas as pd

# 데이터 생성 (일부 결측값 포함)
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [291]:
price = df.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [292]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [293]:
# unstack
import pandas as pd

coffee_data = {
    '커피종류': ['아메리카노', '아메리카노', '아메리카노', '라떼', '라떼', '라떼'],
    '컵크기': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large'],
    '판매량': [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [295]:
g = df.groupby(['커피종류','컵크기'])['판매량'].sum()
g

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [296]:
g.unstack()

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [298]:
g.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

In [299]:
import pandas as pd

# 에피타이저 메뉴
appetizer = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Bread'],
    'Price': [5000, 3000, 2000]
})

# 메인 메뉴
main = pd.DataFrame({
    'Menu': ['Steak', 'Pasta', 'Chicken'],
    'Price': [15000, 12000, 10000]
})

print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [300]:
menu = pd.concat([appetizer,main])
menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [301]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer,main],ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [302]:
# 두 메뉴를 좌우로 연결
full_menu = pd.concat([appetizer,main], axis = 1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [303]:
# 메뉴와 가격
price = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Steak', 'Pasta'],
    'Price': [5000, 3000, 15000, 12000]
})

# 메뉴와 칼로리
cal = pd.DataFrame({
    'Menu': ['Soup', 'Steak', 'Pasta', 'Salad'],
    'Calories': [100, 500, 700, 150]
})

# 두 데이터프레임을 'Menu'를 기준으로 병합
menu_info = pd.merge(price, cal, on='Menu')
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       700

In [304]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
df

   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

In [305]:
pt = df.pivot_table(index='부서',values='급여', aggfunc='mean')
pt

        급여
부서
개발  3000.0
기획  3200.0

In [306]:
# 다양한 집계를 위한 데이터셋
import pandas as pd

df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
print(df)

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [309]:
pp = df.pivot_table(index=['구분',"유형"], columns = "크기", values='수량',aggfunc = 'mean')
pp

크기      대형   소형
구분 유형
가전 일반  4.0  5.0
   특수  7.0  6.0
전자 일반  2.0  1.0
   특수  NaN  3.0

In [310]:
pt = df.pivot_table(
    index = ['구분','유형'],
    columns = '크기',
    values='수량',
    aggfunc='sum',
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6

In [312]:
# 데이터 생성
import pandas as pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024'],
    'Date6': ['2024년02월17일', '2024년02월18일', '2024년02월19일'],
    'DateTime1': ['24-02-17 11:45:30', '24-02-18 12:55:45', '24-02-19 13:30:15'],
    'DateTime2': ['2024-02-17 11-45-30', '2024-02-18 12-55-45', '2024-02-19 13-30-15'],
    'DateTime3': ['02/17/2024 11:45:30 AM', '02/18/2024 12:55:45 PM', '02/19/2024 01:30:15 PM'],
    'DateTime4': ['17 Feb 2024 11:45:30', '18 Feb 2024 12:55:45', '19 Feb 2024 13:30:15']
}

df = pd.DataFrame(data)
df.to_csv("date.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024년02월17일,24-02-17 11:45:30,2024-02-17 11-45-30,02/17/2024 11:45:30 AM,17 Feb 2024 11:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024년02월18일,24-02-18 12:55:45,2024-02-18 12-55-45,02/18/2024 12:55:45 PM,18 Feb 2024 12:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024년02월19일,24-02-19 13:30:15,2024-02-19 13-30-15,02/19/2024 01:30:15 PM,19 Feb 2024 13:30:15

In [314]:
df = pd.read_csv('date.csv')
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024년02월17일,24-02-17 11:45:30,2024-02-17 11-45-30,02/17/2024 11:45:30 AM,17 Feb 2024 11:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024년02월18일,24-02-18 12:55:45,2024-02-18 12-55-45,02/18/2024 12:55:45 PM,18 Feb 2024 12:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024년02월19일,24-02-19 13:30:15,2024-02-19 13-30-15,02/19/2024 01:30:15 PM,19 Feb 2024 13:30:15

In [315]:
print(df['Date1'])

0    2024-02-17
1    2024-02-18
2    2024-02-19
Name: Date1, dtype: object

In [317]:
df['Date1'] = pd.to_datetime(df['Date1'])
print(df['Date1'])

0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date1, dtype: datetime64[ns]

In [320]:
df['Date2'] = pd.to_datetime(df["Date2"], format="%Y:%m:%d")
df['Date2']

0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date2, dtype: datetime64[ns]

In [323]:
df['Date3'] = pd.to_datetime(df['Date3'], format="%y/%m/%d")
df['Date3']

0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date3, dtype: datetime64[ns]

In [324]:
# Date4
print(df['Date4'])
df['Date4'] = pd.to_datetime(df['Date4'])
print(df['Date4'])

0    02/17/2024
1    02/18/2024
2    02/19/2024
Name: Date4, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date4, dtype: datetime64[ns]

In [325]:
# Date5
print(df['Date5'])
df['Date5'] = pd.to_datetime(df['Date5'])
print(df['Date5'])

0    17-Feb-2024
1    18-Feb-2024
2    19-Feb-2024
Name: Date5, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date5, dtype: datetime64[ns]

In [326]:
# Date6
print(df['Date6'])
df['Date6'] = pd.to_datetime(df['Date6'], format="%Y년%m월%d일")
print(df['Date6'])

0    2024년02월17일
1    2024년02월18일
2    2024년02월19일
Name: Date6, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date6, dtype: datetime64[ns]

In [327]:
# DateTime1
print(df['DateTime1'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format="%y-%m-%d %H:%M:%S")
print(df['DateTime1'])

0    24-02-17 11:45:30
1    24-02-18 12:55:45
2    24-02-19 13:30:15
Name: DateTime1, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime1, dtype: datetime64[ns]

In [328]:
# DateTime2
print(df['DateTime2'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format="%Y-%m-%d %H-%M-%S")
print(df['DateTime2'])

0    2024-02-17 11-45-30
1    2024-02-18 12-55-45
2    2024-02-19 13-30-15
Name: DateTime2, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime2, dtype: datetime64[ns]

In [329]:
# DateTime3
print(df['DateTime3'])
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
print(df['DateTime3'])

0    02/17/2024 11:45:30 AM
1    02/18/2024 12:55:45 PM
2    02/19/2024 01:30:15 PM
Name: DateTime3, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime3, dtype: datetime64[ns]

In [330]:
# DateTime4
print(df['DateTime4'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
print(df['DateTime4'])

0    17 Feb 2024 11:45:30
1    18 Feb 2024 12:55:45
2    19 Feb 2024 13:30:15
Name: DateTime4, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime4, dtype: datetime64[ns]

In [331]:
# 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      3 non-null      datetime64[ns]
 1   Date2      3 non-null      datetime64[ns]
 2   Date3      3 non-null      datetime64[ns]
 3   Date4      3 non-null      datetime64[ns]
 4   Date5      3 non-null      datetime64[ns]
 5   Date6      3 non-null      datetime64[ns]
 6   DateTime1  3 non-null      datetime64[ns]
 7   DateTime2  3 non-null      datetime64[ns]
 8   DateTime3  3 non-null      datetime64[ns]
 9   DateTime4  3 non-null      datetime64[ns]
dtypes: datetime64[ns](10)
memory usage: 368.0 bytes

In [332]:
# 년, 월, 일, 시간, 분, 초 추출
df['year'] = df['DateTime4'].dt.year
df['month'] = df['DateTime4'].dt.month
df['day'] = df['DateTime4'].dt.day
df['hour'] = df['DateTime4'].dt.hour
df['minute'] = df['DateTime4'].dt.minute
df['secend'] = df['DateTime4'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,secend
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024,2,17,11,45,30
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024,2,18,12,55,45
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024,2,19,13,30,15

In [333]:
df['DateTime4'].dt.dayofweek

0    5
1    6
2    0
Name: DateTime4, dtype: int32

In [334]:
df['is주말'] = df['DateTime4'].dt.dayofweek >= 5
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,secend,is주말
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024,2,17,11,45,30,True
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024,2,18,12,55,45,True
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024,2,19,13,30,15,False

In [335]:
# 데이터 불러오기 (usecols, parse_dates)
# usecols = 어떤 특정 열만 쓰겠다.
# parse_dates = datetime으로 바꿈
df = pd.read_csv("date.csv", usecols = ['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 11:45:30
1 2024-02-18 12:55:45
2 2024-02-19 13:30:15

In [337]:
day = pd.Timedelta(days=99)
df['100일'] = df['DateTime4'] + day
df

            DateTime4                100일
0 2024-02-17 11:45:30 2024-05-26 11:45:30
1 2024-02-18 12:55:45 2024-05-27 12:55:45
2 2024-02-19 13:30:15 2024-05-28 13:30:15

In [338]:
hour = pd.Timedelta(hours=99)
df['100시간'] = df['DateTime4'] + hour
df

            DateTime4                100일               100시간
0 2024-02-17 11:45:30 2024-05-26 11:45:30 2024-02-21 14:45:30
1 2024-02-18 12:55:45 2024-05-27 12:55:45 2024-02-22 15:55:45
2 2024-02-19 13:30:15 2024-05-28 13:30:15 2024-02-23 16:30:15

In [339]:
# 시간 +/- (3주, 3일, 3시간, 3분 3초 이전과 이후)
diff = pd.Timedelta(weeks=3, days=3, hours=3,minutes=3,seconds=3)
df["+diff"] = df['DateTime4'] + diff
df["-diff"] = df['DateTime4'] - diff
df

,DateTime4,100일,100시간,+diff,-diff
0,2024-02-17 11:45:30,2024-05-26 11:45:30,2024-02-21 14:45:30,2024-03-12 14:48:33,2024-01-24 08:42:27
1,2024-02-18 12:55:45,2024-05-27 12:55:45,2024-02-22 15:55:45,2024-03-13 15:58:48,2024-01-25 09:52:42
2,2024-02-19 13:30:15,2024-05-28 13:30:15,2024-02-23 16:30:15,2024-03-14 16:33:18,2024-01-26 10:27:12

In [341]:
# timedelta 자료형(datetime간의 연산 결과)
diff = df['100일'] - df['100시간']
diff

0   94 days 21:00:00
1   94 days 21:00:00
2   94 days 21:00:00
dtype: timedelta64[ns]

In [342]:
# 기간을 초로 변환 total_seconds()
print(diff.dt.total_seconds()) # 초
print(diff.dt.total_seconds()/60) # 분
print(diff.dt.total_seconds()/60/60) # 시간
print(diff.dt.total_seconds()/60/60/24) # 일

0    8197200.0
1    8197200.0
2    8197200.0
dtype: float64
0    136620.0
1    136620.0
2    136620.0
dtype: float64
0    2277.0
1    2277.0
2    2277.0
dtype: float64
0    94.875
1    94.875
2    94.875
dtype: float64