# 작업형1
- 영상을 멈추고 문제를 먼저 풀어보고, 강의를 시청하세요!

[안내]
- 주어진 문제는 하나의 작업을 단계별로 나누어 제시함. 각 단계는 이전 단계의 결과를 사용함
- FutureWarning은 무시해도 됨


```
# 흔히 발생하는 FutureWarning
# df['views'].fillna(min, inplace=True)  # 변경 전 (경고 발생 가능)
# df['views'] = df['views'].fillna(min)  # 변경 후 (권장 방식)
```

### Section 1. 필터링, 최소값, 중앙값

- 'f5' 컬럼이 0이 아닌 데이터(행)를 구하시오.
- 앞에서 구한 데이터에 ‘views’ 컬럼 결측치를 ‘views’ 컬럼의 최솟값으로 채워주세요.
- 그리고 ‘views’ 컬럼의 중앙값을 계산해 정수로 구하시오.

In [1]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [9]:
cond = df['f5'] != 0
## f5컬럼이 0이 아닌 행
tmp = df[cond]
cond2 = tmp['views'].isnull()

In [15]:
min = tmp['views'].min(numeric_only=True)
tmp[cond2] = min

C:\Users\dnwpg\AppData\Local\Temp\ipykernel_26092\2198734390.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp[cond2] = min

In [17]:
tmp['views'].median()

5924.0

In [18]:
print(int(tmp['views'].median()))

5924

### Section2.카테고리, 인덱스, 문자열 슬라이싱
- 'subscribed' 컬럼에서 가장 빈도수가 많은 날짜를 구하시오.
- 앞에서 구한 날짜의 일(day) 값을 정수로 구하시오.

In [20]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [51]:
df['subscribed'] = pd.to_datetime(df['subscribed'], format = "%Y-%m-%d")
df['subscribed']

0     2024-07-16
1     2024-05-12
2     2024-03-16
3     2024-07-21
4     2024-03-07
         ...
115   2025-02-17
116   2025-02-17
117   2025-02-17
118   2025-02-17
119   2025-02-17
Name: subscribed, Length: 120, dtype: datetime64[ns]

In [60]:
tmp = df['subscribed'].value_counts()
tmp

subscribed
2025-02-17    16
2024-06-21     3
2024-04-03     2
2024-07-29     2
2024-05-28     2
              ..
2024-07-08     1
2024-07-20     1
2024-06-10     1
2024-02-01     1
2024-05-20     1
Name: count, Length: 96, dtype: int64

In [64]:
pd.to_datetime(tmp.idxmax()).day

17

### Section3.파생변수, 정렬, 인덱싱
- 결측치가 있는 데이터(행)를 제거하시오.
- ‘views’ 컬럼을 ‘f1’ 컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
- 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.

In [65]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")

In [75]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [77]:
df = df.dropna()

In [78]:
df['views'] = df['views'] / df['f1']
df

C:\Users\dnwpg\AppData\Local\Temp\ipykernel_26092\292737435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'] = df['views'] / df['f1']

,id,age,city,f1,f2,f3,f4,f5,subscribed,views
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,293.113208
...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,423.782609
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,86.584615
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,105.583333
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,100.661538
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,25.063830

In [84]:
df.sort_values('views',ascending=False)

,id,age,city,f1,f2,f3,f4,f5,subscribed,views
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,423.782609
83,id83,73.0,경기,50.0,1,vip,ENTP,80.138280,2024-09-26,382.780000
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,378.070175
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,350.461538
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,318.916667
...,...,...,...,...,...,...,...,...,...,...
109,id108,21.0,서울,54.0,1,gold,ESTJ,0.000000,2025-02-17,40.333333
57,id57,3.0,대구,111.0,0,silver,ISFJ,29.269869,2024-01-12,39.828829
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,32.277228
108,id107,21.0,부산,76.0,1,silver,ESTJ,0.000000,2025-02-17,30.868421
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,25.063830

In [85]:
ans = 22

### Section4.값 변경, 정렬, 합계

- ‘views’ 컬럼의 결측값(NaN)을 0으로 대체하시오.
- ‘views’ 컬럼을 기준으로 내림차순 정렬하시오.
- 정렬된 상태에서 상위 10개의 값을 모두 10번째로 큰 값으로 대체하시오.
- 최종 ‘views’ 컬럼의 전체 합을 구하고, 정수형으로 출력하시오.

In [112]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")

In [113]:
cond = df['views'].isnull()
df[cond] = 0

In [114]:
tmp = df.sort_values('views',ascending = False).iloc[0:10]
tmp

        id   age city    f1  f2      f3    f4         f5  subscribed    views
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
56    id56  59.0   대구   NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
83    id83  73.0   경기  50.0   1     vip  ENTP  80.138280  2024-09-26  19139.0
32    id32  25.0   부산  64.0   0     vip  ISFJ  13.049921  2024-05-24  17421.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
104  id103  21.0   부산  53.0   0     vip  ISFP   0.000000  2025-02-17  13543.0
114  id113  22.0   경기  34.0   2  silver  ENTP   0.000000  2025-02-17  10346.0
9     id10  95.0   서울  74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
113  id112  22.0   서울  45.0   2     vip  ENTP   0.000000  2025-02-17   9877.0

In [115]:
tmp['views'] = 9877.0

In [117]:
ans = tmp['views'].sum()
print(int(ans))

98770

### Section 5. 문자열 슬라이싱, 파생변수, 평균값
- ‘f4’컬럼의 값 중에서 3번째와 4번째 문자가 ‘FJ’인 행(데이터)를 찾으시오.
- 찾은 데이터 중에서 ‘f2’ 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [118]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [126]:
cond = df['f4'].str[2:4] == "FJ"
tmp = df[cond]
ans = tmp['f2'].mean()
print(round(ans,2))

0.61

### Section6. 필터링, 분산

- ‘f3’ 컬럼이 gold이면서 ‘f2’ 컬럼이 2인 데이터를 찾으시오.
- 찾은 데이터에서 ‘f1’ 컬럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [127]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [133]:
cond = (df['f3'] == "gold") & (df['f2'] == 2)
ans = df[cond]['f1'].var()

In [134]:
print(round(ans,2))

235.43

### Section7.값 변경(연산), 필터링 절대값
- 모든 나이(age)에 1을 더하시오.
- 20대의 ‘views’ 평균과 30대의 ‘views’ 평균의 절댓값 차이를 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [135]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [148]:
df['age'] = df['age'] + 1
cond1 = (20 <= df['age']) & (df['age'] < 30)

cond2 = (30 <= df['age']) & (df['age'] < 40)

cond1

0      False
1      False
2      False
3      False
4      False
       ...
115     True
116    False
117    False
118    False
119    False
Name: age, Length: 120, dtype: bool

In [151]:
a = df[cond1]['views'].mean()

In [152]:
b = df[cond2]['views'].mean()

In [153]:
print(round(a-b),2)

1002 2

### Section8. 시계열 데이터, 필터링, 데이터 개수

- ‘subscribed’ 컬럼이 2024년 2월인 데이터를 찾으시오.
- 위에서 찾은 데이터 중 ‘f3’ 컬럼이 gold인 데이터의 개수를 구하시오.

In [154]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [156]:
df['subscribed'] = pd.to_datetime(df['subscribed'])

- ‘subscribed’ 컬럼이 2024년 2월인 데이터를 찾으시오.
- 위에서 찾은 데이터 중 ‘f3’ 컬럼이 gold인 데이터의 개수를 구하시오.

In [159]:
cond = (df['subscribed'].dt.year == 2024) & (df['subscribed'].dt.month == 2)
df[cond]

        id   age city    f1  f2      f3    f4         f5 subscribed    views
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0
22    id22  -6.3   부산  72.0   1    gold  ENFP  52.667078 2024-02-09   6147.0
31    id31  86.0   부산  77.0   0    gold  ESFJ  73.586397 2024-02-11   8014.0
34    id34  65.0   부산   NaN   1  silver  INFP  48.431184 2024-02-01   3163.0
42    id42  65.0   대구  48.0   2    gold  ESTP  33.308999 2024-02-09   5999.0
55    id55  75.0   대구  63.0   2    gold  ENTP  13.049921 2024-02-06   6042.0
61    id61  87.0   경기  62.0   2     NaN  INTP  69.730313 2024-02-03    218.0
64    id64  43.0   경기  62.0   2    gold  ESFP  73.586397 2024-02-22   5995.0
86    id86   2.0   경기   NaN   0     NaN  ESTP  29.269869 2024-02-16   2155.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0

In [160]:
df[cond]['f3'].value_counts()

f3
gold      5
vip       2
silver    1
Name: count, dtype: int64

In [161]:
ans = 5

### Section9. 필터링, 카테고리, 최빈값

- ‘views’ 컬럼 값이 1000 이하인 데이터(결측치 제외)를 찾으시오.
- 앞에서 구한 데이터 중 ‘f4’ 컬럼의 최빈값을 구하시오.

In [162]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [163]:
cond = df['views'] <= 1000
df[cond]['f4'].mode()[0]

'ISFJ'

### Section10. 그룹핑, 최대값, 정렬
- 결측치가 있는 행을 삭제하시오.
- 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
- 앞에서 계산한 지역별 평균 데이터에서 'f2' 컬럼 값이 가장 큰 지역을 구하시오.

In [164]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df = df.dropna()
df

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [168]:
df.groupby(['city']).mean(numeric_only=True)

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

In [169]:
ans = "서울"

### Section11. 슬라이싱, 사분위수, 결측치 제거

- 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
- 결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
- 앞에서 구한 70% 데이터 중 ‘views’ 컬럼의 3사분위수에서 1사분위수를 뺀 값을 소수점 이하를 버리고 정수 부분만 구하시오.

In [170]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df = df.dropna()

In [175]:
l = int(len(df) * (0.7))
df = df.iloc[:l]

In [176]:
a = df['views'].quantile(0.75)
b = df['views'].quantile(0.25)

In [177]:
print(int(a-b))

2771

### Section12.결측치 처리, 최빈값, 데이터 개수

- 결측치가 가장 많은 두 컬럼을 찾으시오.
첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.
- 두 번째로 결측치가 많은 컬럼의 결측값을 그 컬럼의 최빈값으로 대체하시오.
- ‘f3’ 컬럼의 ‘gold’ 값을 가진 데이터의 수를 정수형으로 구하시오.

In [181]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
print(df.isnull().sum())

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [184]:
df = df.dropna(subset=['f1'])
#print(df['f3'].mode())
freq = df['f3'].mode()[0]
df['f3'] = df['f3'].fillna(freq)

In [185]:
print(sum(df['f3'] == 'gold'))

63

### Section13. 결측 데이터 찾기, 필터링, 평균값
- ‘f1’ 컬럼에 결측치가 있는 데이터만 선택하시오.
- 선택된 데이터에서 ‘age’ 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 자리까지 계산)

In [188]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
cond = df['f1'].isnull()
a = df[cond]['age'].mean()
print(round(a,1))

53.6

### Section14.중복데이터 제거, 값 변경, 데이터 개수

- 중복 데이터를 제거하시오. (단, 중복이 발생한 경우 뒤에 나온 행을 제거한다.)
- ‘f3’ 컬럼의 결측치는 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.
- 변환된 ‘f3’ 컬럼의 총합을 정수형으로 구하시오.

In [190]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")
df = df.drop_duplicates()

In [191]:
cond1 = df['f3'].isnull()
cond2 = df['f3'] == "silver"
cond3 = df['f3'] == "gold"
cond4 = df['f3'] == "vip"


df[cond1] = 0
df[cond2] = 1
df[cond3] = 2
df[cond4] = 3

result = df['f3'].sum()
print(int(result))

167

### Section15. 컬럼 삭제, 행 단위 합계, 필터링
- 주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.
- 숫자 자료형 컬럼의 결측치를 0으로 대체하시오.
- 각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오. (각 행의 합: ‘age’ + ‘f1’ + ‘f2’ + ‘f5’ + ‘views’)

In [192]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p1/type1_data1.csv")

cols = df.select_dtypes(exclude="object").columns

df = df[cols]

df = df.fillna(0)

df = df.T

print(sum(df.sum() > 3000))

88