### mart 판매 데이터를 기반으로 판매액을 예측하시오.
- 제공된 데이터 목록: mart_train.csv (훈련 데이터), mart_test.csv (평가용 데이터)
- 예측할 컬럼: total (총 판매액)
학습용 데이터(mart_train.csv)를 이용하여 총 판매액을 예측하는 모델을 만든 후, 이를 평가용 데이터(mart_test.csv)에 적용하여 얻은 예측값을 다음과 같은 형식의 CSV 파일로 생성하시오.
- 제출 파일은 다음 한 개의 컬럼을 포함해야 합니다.
- pred: 예측된 총 판매액
- 제출 파일명: 'result.csv'
- 제출한 모델의 성능은 RMSE(Root Mean Square Error) 평가지표에 따라 채점한다.
- 제출 CSV 파일명 및 형태: result.csv

~~~
pred
10000
20000
30000
40000
...
~~~

### 답안 제출 참고
- pd.read_csv('result.csv') 로 제출 코드 확인

# 1. 문제정의
- RMSE
- target: total
- 예측 파일명: result.csv
- 컬럼 1개(pred)

# 2. 라이브러리 및 데이터 불러오기

In [49]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/7_2/mart_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/7_2/mart_test.csv")

# 3. 탐색적 데이터 분석(EDA)

In [50]:
# 데이터 크기 확인
print(train.shape,test.shape)

(700, 10) (300, 9)

In [51]:
# train 샘플 확인
train.head()

,branch,city,customer_type,gender,product_line,total,payment_method,rating,time_of_day,day_name
0,A,Yangon,Member,Female,Health and beauty,823457.25,Ewallet,9.1,afternoon,Saturday
1,C,Naypyitaw,Normal,Female,Electronic accessories,120330.00,Cash,9.6,morning,Friday
2,A,Yangon,Normal,Male,Home and lifestyle,510788.25,Credit card,7.4,afternoon,Sunday
3,A,Yangon,Member,Male,Health and beauty,733572.00,Ewallet,8.4,evening,Sunday
4,A,Yangon,Normal,Male,Sports and travel,951567.75,Ewallet,5.3,morning,Friday

In [52]:
# test 샘플 확인
test.head()

,branch,city,customer_type,gender,product_line,payment_method,rating,time_of_day,day_name
0,C,Naypyitaw,Normal,Female,Fashion accessories,Ewallet,9.6,afternoon,Thursday
1,B,Mandalay,Normal,Male,Food and beverages,Credit card,4.3,evening,Wednesday
2,B,Mandalay,Member,Female,Fashion accessories,Credit card,5.0,evening,Wednesday
3,B,Mandalay,Member,Male,Health and beauty,Cash,9.2,morning,Sunday
4,B,Mandalay,Member,Female,Home and lifestyle,Cash,6.3,afternoon,Saturday

In [53]:
# 자료형 확인
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   branch          700 non-null    object
 1   city            700 non-null    object
 2   customer_type   700 non-null    object
 3   gender          700 non-null    object
 4   product_line    700 non-null    object
 5   total           700 non-null    float64
 6   payment_method  700 non-null    object
 7   rating          700 non-null    float64
 8   time_of_day     700 non-null    object
 9   day_name        700 non-null    object
dtypes: float64(2), object(8)
memory usage: 54.8+ KB

In [54]:
# train 기초 통계값 확인
train.describe()

              total      rating
count  7.000000e+02  700.000000
mean   4.850780e+05    7.003429
std    3.643907e+05    1.713078
min    1.904175e+04    4.000000
25%    2.001195e+05    5.500000
50%    3.818745e+05    7.000000
75%    7.061276e+05    8.425000
max    1.563975e+06   10.000000

In [55]:
# test 기초 통계값 확인
test.describe()

           rating
count  300.000000
mean     6.901000
std      1.732099
min      4.000000
25%      5.500000
50%      6.800000
75%      8.500000
max     10.000000

In [56]:
# train 기초 통계값 (Object)

In [57]:
# test 기초 통계값 (Object)
train.nunique()

branch              3
city                3
customer_type       2
gender              2
product_line        6
total             695
payment_method      3
rating             61
time_of_day         3
day_name            7
dtype: int64

In [58]:
# train 결측치
train.isnull().sum()

branch            0
city              0
customer_type     0
gender            0
product_line      0
total             0
payment_method    0
rating            0
time_of_day       0
day_name          0
dtype: int64

In [59]:
# test 결측치
test.isnull().sum()

branch            0
city              0
customer_type     0
gender            0
product_line      0
payment_method    0
rating            0
time_of_day       0
day_name          0
dtype: int64

In [60]:
# 타겟 (value_count())

In [61]:
# target (분포)

In [62]:
# target (분포, 시각화)

In [63]:
train.head()

,branch,city,customer_type,gender,product_line,total,payment_method,rating,time_of_day,day_name
0,A,Yangon,Member,Female,Health and beauty,823457.25,Ewallet,9.1,afternoon,Saturday
1,C,Naypyitaw,Normal,Female,Electronic accessories,120330.00,Cash,9.6,morning,Friday
2,A,Yangon,Normal,Male,Home and lifestyle,510788.25,Credit card,7.4,afternoon,Sunday
3,A,Yangon,Member,Male,Health and beauty,733572.00,Ewallet,8.4,evening,Sunday
4,A,Yangon,Normal,Male,Sports and travel,951567.75,Ewallet,5.3,morning,Friday

# 4. 데이터 전처리

In [64]:
# target
target = train.pop("total")
target

0       823457.25
1       120330.00
2       510788.25
3       733572.00
4       951567.75
          ...
695     688038.75
696     170352.00
697     391797.00
698     986296.50
699    1535625.00
Name: total, Length: 700, dtype: float64

In [65]:
train.head()

,branch,city,customer_type,gender,product_line,payment_method,rating,time_of_day,day_name
0,A,Yangon,Member,Female,Health and beauty,Ewallet,9.1,afternoon,Saturday
1,C,Naypyitaw,Normal,Female,Electronic accessories,Cash,9.6,morning,Friday
2,A,Yangon,Normal,Male,Home and lifestyle,Credit card,7.4,afternoon,Sunday
3,A,Yangon,Member,Male,Health and beauty,Ewallet,8.4,evening,Sunday
4,A,Yangon,Normal,Male,Sports and travel,Ewallet,5.3,morning,Friday

In [66]:
test.head()

,branch,city,customer_type,gender,product_line,payment_method,rating,time_of_day,day_name
0,C,Naypyitaw,Normal,Female,Fashion accessories,Ewallet,9.6,afternoon,Thursday
1,B,Mandalay,Normal,Male,Food and beverages,Credit card,4.3,evening,Wednesday
2,B,Mandalay,Member,Female,Fashion accessories,Credit card,5.0,evening,Wednesday
3,B,Mandalay,Member,Male,Health and beauty,Cash,9.2,morning,Sunday
4,B,Mandalay,Member,Female,Home and lifestyle,Cash,6.3,afternoon,Saturday

In [69]:
# 원핫인코딩
x = pd.concat([train,test],axis=0)
x = pd.get_dummies(x)
train = x.iloc[:len(train)]
test = x.iloc[len(train):]
train.shape, test.shape

((700, 88), (300, 88))

In [74]:
train

,rating,branch_A_False,branch_A_True,branch_B_False,branch_B_True,branch_C_False,branch_C_True,city_Mandalay_False,city_Mandalay_True,city_Naypyitaw_False,...,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,day_name_Friday,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday
0,9.1,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,9.6,True,False,True,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,7.4,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
3,8.4,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
4,5.3,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,6.6,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
696,6.9,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
697,4.3,True,False,False,True,True,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
698,7.8,False,True,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
699,8.0,True,False,True,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [71]:
test.head()

,rating,branch_A_False,branch_A_True,branch_B_False,branch_B_True,branch_C_False,branch_C_True,city_Mandalay_False,city_Mandalay_True,city_Naypyitaw_False,...,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,day_name_Friday,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday
0,9.6,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
1,4.3,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
2,5.0,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
3,9.2,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
4,6.3,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False

# 5. 검증 데이터 분할

In [73]:
# 검증데이터 분할
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.1,
    random_state= 0
)
x_tr.shape

(630, 88)

# 6. 머신러닝 학습 및 평가

In [ ]:
# RMSE

In [ ]:
# 선형회귀

In [82]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state = 0)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val) 

from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_val,pred)

384672.76776113245

In [ ]:
# Xgboost

In [85]:
# LightGBM
import lightgbm as lgb
rf = lgb.LGBMRegressor(random_state = 0,verbose = -1)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val) 

from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_val,pred)

418425.4725000017

# 7. 예측 및 결과 파일 생성

In [ ]:
# test예측 및 csv 생성

In [ ]:
# result.csv 확인

# [심화] 성능 개선

In [ ]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/7_2/mart_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/7_2/mart_test.csv")

# target 데이터


# 레이블 인코딩


# 검증데이터 분리


# 선형회귀


# 랜덤포레스트


# Xgboost


# LightGBM


# 최종 제출 파일