## Section14. 문자열

In [2]:
import pandas as pd
df = pd.DataFrame({"A":['데이터 분석','기본 학습서','퇴근 후 열공'],
                   "B":[10,20,30],
                   "C":['ab cd','AB CD','ab cd ']
                   })
df

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [3]:
# 문자의 일부는 .replace로 X
df['A'] = df['A'].replace("분석", "시각화")
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [4]:
df['A'] = df['A'].str.replace('분석','시각화')
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [5]:
# 에러
# df['B'] = df['B'].str.replace(10,20)
# df

In [6]:
# 문자열 분리
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [7]:
# 앞쪽 or 뒤쪽
df['A'].str.split()[0]

['데이터', '시각화']

In [8]:
df['D'] = df['A'].str.split().str[0]
df

         A   B       C    D
0  데이터 시각화  10   ab cd  데이터
1   기본 학습서  20   AB CD   기본
2  퇴근 후 열공  30  ab cd    퇴근

In [9]:
# 문자 검색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [10]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A   B       C    D  기본포함유무
0  데이터 시각화  10   ab cd  데이터   False
1   기본 학습서  20   AB CD   기본    True
2  퇴근 후 열공  30  ab cd    퇴근   False

In [11]:
# 단어의 일부로는 못찾음
menu = pd.Series(['맛난버거 세트','매운 치킨버거','더블 치즈버거'])
menu.isin(['맛난버거 세트','더블 치즈버거'])

0     True
1    False
2     True
dtype: bool

In [12]:
# 단어의 일부로 찾을 수 있음
menu.str.contains('세트')

0     True
1    False
2    False
dtype: bool

In [13]:
'AB cd' == 'ab CD'

False

In [14]:
df['C'] = df['C'].str.lower()
df['C']

0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object

In [15]:
df['C'] = df['C'].str.upper()
df['C']

0     AB CD
1     AB CD
2    AB CD
Name: C, dtype: object

In [16]:
df['C'] == 'AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [17]:
## str을 반드시붙여야함. 왜냐면 일부만 적용을 하는거기 때문임.
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(" ","")
df['C']

0    abcd
1    abcd
2    abcd
Name: C, dtype: object

In [18]:
df['C'].str[1:3]

0    bc
1    bc
2    bc
Name: C, dtype: object

In [19]:
df['C'][1:3]

1    abcd
2    abcd
Name: C, dtype: object

## Section15. 내장함수

In [20]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [21]:
# 행의 수
print(len(df))
print(df.shape[0])

8
8

In [22]:
cond = df['가격'] > 5000

# sum으로 조건에 맞는 개수 구하기
print(sum(cond))

# len으로 조건에 맞는 개수 구하기 
print(len(df[cond]))

4
4

In [23]:
df

        메뉴    가격  칼로리    원산지    이벤트가
0    아메리카노  4500   10   콜롬비아     NaN
1     카페라떼  5000  110  코스타리카  1000.0
2     카페모카  5500  250  코스타리카  1000.0
3     카푸치노  5000  110  코스타리카     NaN
4    에스프레소  4000   20  코스타리카     NaN
5      밀크티  5900  210  코스타리카     NaN
6       녹차  5300    0   대한민국     NaN
7  크리스마스라떼  6000  300     한국     NaN

In [24]:
# 열 별 합계
df.sum(numeric_only=True)

가격      41200.0
칼로리      1010.0
이벤트가     2000.0
dtype: float64

In [25]:
# 행 별 합계
df.sum(axis = 1, numeric_only=True)

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    6300.0
dtype: float64

In [26]:
print("최대값: ",df['가격'].max())
print("최소값: ",df['가격'].min())
print("평균값: ",df['가격'].mean())
print("중앙값: ",df['가격'].median())
print("합계: ",df['가격'].sum())
print("표준편차: ",df['가격'].std())
print("분산: ",df['가격'].var)

최대값:  6000
최소값:  4000
평균값:  5150.0
중앙값:  5150.0
합계:  41200
표준편차:  678.2329983125268
분산:  <bound method Series.var of 0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
7    6000
Name: 가격, dtype: int64>

In [27]:
# 1사분위수
print("분위수 25% 값", df['가격'].quantile(.25))
# 3사분위수
print("분위수 75% 값", df['가격'].quantile(.75))

분위수 25% 값 4875.0
분위수 75% 값 5600.0

In [28]:
# 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
0  아메리카노  4500   10   콜롬비아   NaN
4  에스프레소  4000   20  코스타리카   NaN

In [29]:
# 상위 25% 데이터
cond = df['가격'].quantile(.75) < df['가격']
df[cond]

        메뉴    가격  칼로리    원산지  이벤트가
5      밀크티  5900  210  코스타리카   NaN
7  크리스마스라떼  6000  300     한국   NaN

In [30]:
# 최빈값 구히기(여러개가 동일할수도있기떄문에 Series로 찾음)
df['원산지'].mode()[0]

'코스타리카'

In [31]:
# 가격에서 가장 큰 index값 반환
df['가격'].idxmax()

7

In [32]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

메뉴      크리스마스라떼
가격         6000
칼로리         300
원산지          한국
이벤트가        NaN
Name: 7, dtype: object

In [33]:
df.loc[max_ind,"메뉴"]

'크리스마스라떼'

In [34]:
df.nlargest(3,'가격')

        메뉴    가격  칼로리    원산지    이벤트가
7  크리스마스라떼  6000  300     한국     NaN
5      밀크티  5900  210  코스타리카     NaN
2     카페모카  5500  250  코스타리카  1000.0

In [35]:
df.nsmallest(3,'가격')

      메뉴    가격  칼로리    원산지    이벤트가
4  에스프레소  4000   20  코스타리카     NaN
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [36]:
# apply 적용해서 새로운 컬럼 적용하기
def cal(x):
    if x >= 100:
        return "No"
    else:
        return "Yes"

df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

        메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0    아메리카노  4500   10   콜롬비아     NaN     Yes
1     카페라떼  5000  110  코스타리카  1000.0      No
2     카페모카  5500  250  코스타리카  1000.0      No
3     카푸치노  5000  110  코스타리카     NaN      No
4    에스프레소  4000   20  코스타리카     NaN     Yes
5      밀크티  5900  210  코스타리카     NaN      No
6       녹차  5300    0   대한민국     NaN     Yes
7  크리스마스라떼  6000  300     한국     NaN      No

In [37]:
import pandas as pd

df = pd.DataFrame({
    'Name': {0: '쿼카', 1: '알파카', 2: '시바견'},
    '수학': {0: 90, 1: 93, 2: 85},
    '영어': {0: 92, 1: 84, 2: 86},
    '국어': {0: 91, 1: 94, 2: 83},
})

df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [38]:
# melt로 재구조 이름을 기준으로 변경
pd.melt(df, id_vars='Name')

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [39]:
pd.melt(df, id_vars='Name',value_vars=['수학','영어'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [40]:
pd.melt(df, id_vars='Name',var_name='과목',value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [41]:
import pandas as pd

df = pd.DataFrame({
    "반": ["A반", "A반", "B반"],   # 반 정보 추가
    "이름": ["쿼카", "알파카", "시바견"],
    "수학": [90, 93, 85],
    "영어": [92, 84, 86],
    "국어": [91, 94, 83]
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [42]:
pd.melt(df, id_vars=['반','이름'],var_name='과목',value_name='점수')

    반   이름  과목  점수
0  A반   쿼카  수학  90
1  A반  알파카  수학  93
2  B반  시바견  수학  85
3  A반   쿼카  영어  92
4  A반  알파카  영어  84
5  B반  시바견  영어  86
6  A반   쿼카  국어  91
7  A반  알파카  국어  94
8  B반  시바견  국어  83