## Section9. 데이터 추가/변경

In [1]:
import pandas as pd

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [4]:
# 결측값으로 추가, 원두 컬럼을 만들고 결측값(NaN)으로 대입
import numpy as np
df['원산지'] = np.nan
df.head(4)

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN

In [5]:
# 아메리카노의 원두는 '콜롬비아' 데이터 추가
df.loc[0,"원산지"] = "콜롬비아"

C:\Users\dnwpg\AppData\Local\Temp\ipykernel_21708\2555508939.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0,"원산지"] = "콜롬비아"

In [22]:
df.head()

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250   NaN
3   카푸치노  5000  110   NaN
4  에스프레소  4000   20   NaN

In [23]:
# 딕셔너리 형태로 데이터(행) 추가
# 비어있는애는 결측치로 채워짐
df.loc['시즌'] = {"메뉴" : '딴짓커피','가격' : 2000, '칼로리':20}

In [24]:
df.tail(2)

         메뉴    가격  칼로리  원산지
7   크리스마스라떼  6000  300   한국
시즌     딴짓커피  2000   20  NaN

In [25]:
# 리스트 형태로 데이터(행) 추가
df.loc[7] = ['크리스마스라떼',6000,300,'한국']

In [26]:
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250   NaN
3      카푸치노  5000  110   NaN
4     에스프레소  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
7   크리스마스라떼  6000  300    한국
시즌     딴짓커피  2000   20   NaN

In [27]:
# cafe2 저장
df = df.drop("시즌", axis = 0)
df.to_csv('cafe2.csv',index=False)

## Section10. 정렬

In [47]:
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [48]:
# 인덱스 기준(기본값 ascending=True(오름차순))
df.sort_index(ascending=False)

        메뉴    가격  칼로리   원산지
7  크리스마스라떼  6000  300    한국
6       녹차  5300    0   NaN
5      밀크티  5900  210   NaN
4    에스프레소  4000   20   NaN
3     카푸치노  5000  110   NaN
2     카페모카  5500  250   NaN
1     카페라떼  5000  110   NaN
0    아메리카노  4500   10  콜롬비아

In [49]:
# 값 기준(기본값 ascending=True(오름차순))
# 메뉴 기준 정렬
df.sort_values('메뉴',ascending=False)

        메뉴    가격  칼로리   원산지
7  크리스마스라떼  6000  300    한국
3     카푸치노  5000  110   NaN
2     카페모카  5500  250   NaN
1     카페라떼  5000  110   NaN
4    에스프레소  4000   20   NaN
0    아메리카노  4500   10  콜롬비아
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN

In [50]:
# 가격과 메뉴 기준 정렬
# 가격을 내림차순으로 정렬하다가 만약 같은값이있으면 메뉴는 오름차순으로 정렬
# 대입연산자로 넣어줘야함.
df = df.sort_values(['가격','메뉴'],ascending=[False,True])

In [51]:
# 인덱스 새로 만들기 drop = True
# 새로안하면 그냥 옆에다가 생겨버림
df.reset_index(drop=True)

        메뉴    가격  칼로리   원산지
0  크리스마스라떼  6000  300    한국
1      밀크티  5900  210   NaN
2     카페모카  5500  250   NaN
3       녹차  5300    0   NaN
4     카페라떼  5000  110   NaN
5     카푸치노  5000  110   NaN
6    아메리카노  4500   10  콜롬비아
7    에스프레소  4000   20   NaN

In [52]:
df.reset_index(drop=False)

   index       메뉴    가격  칼로리   원산지
0      7  크리스마스라떼  6000  300    한국
1      5      밀크티  5900  210   NaN
2      2     카페모카  5500  250   NaN
3      6       녹차  5300    0   NaN
4      1     카페라떼  5000  110   NaN
5      3     카푸치노  5000  110   NaN
6      0    아메리카노  4500   10  콜롬비아
7      4    에스프레소  4000   20   NaN

## Section11. 필터링

In [53]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [54]:
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7    False
Name: 칼로리, dtype: bool

In [55]:
# 1개 조건
cond = df['칼로리'] < 50
df[cond]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN

In [56]:
# 1개 조건
df[df['칼로리'] < 50]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN

In [57]:
# 칼로리 50 이상
cond = df['칼로리'] < 50
df[~cond]

        메뉴    가격  칼로리  원산지
1     카페라떼  5000  110  NaN
2     카페모카  5500  250  NaN
3     카푸치노  5000  110  NaN
5      밀크티  5900  210  NaN
7  크리스마스라떼  6000  300   한국

In [58]:
# 2개 이상 일때(AND)
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1 & cond2]

        메뉴    가격  칼로리  원산지
1     카페라떼  5000  110  NaN
2     카페모카  5500  250  NaN
3     카푸치노  5000  110  NaN
5      밀크티  5900  210  NaN
7  크리스마스라떼  6000  300   한국

In [59]:
# 2개 이상 일떄(OR)
df[cond1 | cond2]

        메뉴    가격  칼로리  원산지
1     카페라떼  5000  110  NaN
2     카페모카  5500  250  NaN
3     카푸치노  5000  110  NaN
5      밀크티  5900  210  NaN
6       녹차  5300    0  NaN
7  크리스마스라떼  6000  300   한국

In [66]:
# 문자열 1개 조건
# 원두 == 콜롬비아
cond = (df['원산지'] == "한국")
df[cond]

        메뉴    가격  칼로리 원산지
7  크리스마스라떼  6000  300  한국

In [68]:
# 문자열과 숫자 조건(AND)
cond1 = (df['원산지'] == "한국")
cond2 = df['가격'] >= 6000
df[cond1 & cond2]

        메뉴    가격  칼로리 원산지
7  크리스마스라떼  6000  300  한국

In [69]:
df

        메뉴    가격  칼로리   원산지
0    아메리카노  4500   10  콜롬비아
1     카페라떼  5000  110   NaN
2     카페모카  5500  250   NaN
3     카푸치노  5000  110   NaN
4    에스프레소  4000   20   NaN
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN
7  크리스마스라떼  6000  300    한국

In [70]:
df['메뉴'].isin(['녹차'])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [71]:
cond = df['메뉴'].isin(['녹차'])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300    0  NaN

In [74]:
box = ['녹차','카푸치노','카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

     메뉴    가격  칼로리  원산지
1  카페라떼  5000  110  NaN
3  카푸치노  5000  110  NaN
6    녹차  5300    0  NaN

## Section12. 결측치 처리

In [76]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df

        메뉴    가격  칼로리   원산지
0    아메리카노  4500   10  콜롬비아
1     카페라떼  5000  110   NaN
2     카페모카  5500  250   NaN
3     카푸치노  5000  110   NaN
4    에스프레소  4000   20   NaN
5      밀크티  5900  210   NaN
6       녹차  5300    0   NaN
7  크리스마스라떼  6000  300    한국

In [77]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False  False   True
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False  False

In [78]:
# 컬럼별 결측치 확인
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    6
dtype: int64

In [79]:
# 컬럼별 결측치 확인
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    6
dtype: int64

In [80]:
# 결측값 채우기
df['원산지'] = df['원산지'].fillna('코스타리카')
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [81]:
df.to_csv('cafe3.csv',index=False)

## Section13. 값 변경

In [83]:
df = pd.read_csv("cafe3.csv")
df.head()

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250  코스타리카
3   카푸치노  5000  110  코스타리카
4  에스프레소  4000   20  코스타리카

In [85]:
# 문자 변경 : 아메리카노 -> 룽고, 녹차 -> 그린티
df = df.replace("아메리카노", "룽고")
df = df.replace("녹차", "그린티")
df

        메뉴    가격  칼로리    원산지
0       룽고  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6      그린티  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [86]:
change = {'룽고':'아메리카노','그린티':'녹차'}
df = df.replace(change)

In [87]:
df

        메뉴    가격  칼로리    원산지
0    아메리카노  4500   10   콜롬비아
1     카페라떼  5000  110  코스타리카
2     카페모카  5500  250  코스타리카
3     카푸치노  5000  110  코스타리카
4    에스프레소  4000   20  코스타리카
5      밀크티  5900  210  코스타리카
6       녹차  5300    0  코스타리카
7  크리스마스라떼  6000  300     한국

In [89]:
# loc로 값 변경하기
df.loc[6,"원산지"] = "대한민국"
df.tail(3)

        메뉴    가격  칼로리    원산지
5      밀크티  5900  210  코스타리카
6       녹차  5300    0   대한민국
7  크리스마스라떼  6000  300     한국

In [90]:
# 이벤트가 전체 1000으로 변경
df.loc[1:2,'이벤트가'] = 1000
df.head()

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250  코스타리카  1000.0
3   카푸치노  5000  110  코스타리카     NaN
4  에스프레소  4000   20  코스타리카     NaN

In [91]:
df.to_csv('cafe4.csv',index=False)

In [92]:
# map() 함수
import pandas as pd
df = pd.DataFrame({"만족도" : ["만족","보통","불만","보통","만족"]})

mapping = {"만족":3,"보통":2,"불만":1}
df['만족도 조사'] = df['만족도'].map(mapping)
df

  만족도  만족도 조사
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3