## 시계열 데이터

In [26]:
# 데이터 생성(실습 전 실행)
import pandas as pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024'],
    'Date6': ['2024년02월17일', '2024년02월18일', '2024년02월19일'],
    'DateTime1': ['24-02-17 11:45:30', '24-02-18 12:55:45', '24-02-19 13:30:15'],
    'DateTime2': ['2024-02-17 11-45-30', '2024-02-18 12-55-45', '2024-02-19 13-30-15'],
    'DateTime3': ['02/17/2024 11:45:30 AM', '02/18/2024 12:55:45 PM', '02/19/2024 01:30:15 PM'],
    'DateTime4': ['17 Feb 2024 11:45:30', '18 Feb 2024 12:55:45', '19 Feb 2024 13:30:15']
}

df = pd.DataFrame(data)
df.to_csv("date.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024년02월17일,24-02-17 11:45:30,2024-02-17 11-45-30,02/17/2024 11:45:30 AM,17 Feb 2024 11:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024년02월18일,24-02-18 12:55:45,2024-02-18 12-55-45,02/18/2024 12:55:45 PM,18 Feb 2024 12:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024년02월19일,24-02-19 13:30:15,2024-02-19 13-30-15,02/19/2024 01:30:15 PM,19 Feb 2024 13:30:15

In [27]:
# 데이터 불러오기
df = pd.read_csv("date.csv")
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024년02월17일,24-02-17 11:45:30,2024-02-17 11-45-30,02/17/2024 11:45:30 AM,17 Feb 2024 11:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024년02월18일,24-02-18 12:55:45,2024-02-18 12-55-45,02/18/2024 12:55:45 PM,18 Feb 2024 12:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024년02월19일,24-02-19 13:30:15,2024-02-19 13-30-15,02/19/2024 01:30:15 PM,19 Feb 2024 13:30:15

In [28]:
# Date1
print(df['Date1'])
df['Date1'] = pd.to_datetime(df['Date1'])
print(df['Date1'])

0    2024-02-17
1    2024-02-18
2    2024-02-19
Name: Date1, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date1, dtype: datetime64[ns]

In [29]:
# Date2
'''
print(df['Date2'])
df['Date2'] = pd.to_datetime(df['Date2'])
print(df['Date2'])'''


print(df['Date2'])
df['Date2'] = pd.to_datetime(df['Date2'], format="%Y:%m:%d")
print(df['Date2'])

0    2024:02:17
1    2024:02:18
2    2024:02:19
Name: Date2, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date2, dtype: datetime64[ns]

In [30]:
# Date3 (year 2자리: %y)
print(df['Date3'])
df['Date3'] = pd.to_datetime(df['Date3'], format = "%y/%m/%d")
print(df['Date3'])

0    24/02/17
1    24/02/18
2    24/02/19
Name: Date3, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date3, dtype: datetime64[ns]

In [31]:
# Date4
print(df['Date4'])
df['Date4'] = pd.to_datetime(df['Date4'])
print(df['Date4'])

0    02/17/2024
1    02/18/2024
2    02/19/2024
Name: Date4, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date4, dtype: datetime64[ns]

In [32]:
# Date5
print(df['Date5'])
df['Date5'] = pd.to_datetime(df['Date5'])
print(df['Date5'])

0    17-Feb-2024
1    18-Feb-2024
2    19-Feb-2024
Name: Date5, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date5, dtype: datetime64[ns]

In [33]:
# Date6
print(df['Date6'])
df['Date6'] = pd.to_datetime(df['Date6'], format="%Y년%m월%d일")
print(df['Date6'])

0    2024년02월17일
1    2024년02월18일
2    2024년02월19일
Name: Date6, dtype: object
0   2024-02-17
1   2024-02-18
2   2024-02-19
Name: Date6, dtype: datetime64[ns]

In [34]:
# DateTime1
print(df['DateTime1'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format="%y-%m-%d %H:%M:%S")
print(df['DateTime1'])

0    24-02-17 11:45:30
1    24-02-18 12:55:45
2    24-02-19 13:30:15
Name: DateTime1, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime1, dtype: datetime64[ns]

In [35]:
# DateTime2
print(df['DateTime2'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format="%Y-%m-%d %H-%M-%S")
print(df['DateTime2'])

0    2024-02-17 11-45-30
1    2024-02-18 12-55-45
2    2024-02-19 13-30-15
Name: DateTime2, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime2, dtype: datetime64[ns]

In [37]:
# DateTime3
print(df['DateTime3'])
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
print(df['DateTime3'])

0    02/17/2024 11:45:30 AM
1    02/18/2024 12:55:45 PM
2    02/19/2024 01:30:15 PM
Name: DateTime3, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime3, dtype: datetime64[ns]

In [38]:
# DateTime4
print(df['DateTime4'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
print(df['DateTime4'])

0    17 Feb 2024 11:45:30
1    18 Feb 2024 12:55:45
2    19 Feb 2024 13:30:15
Name: DateTime4, dtype: object
0   2024-02-17 11:45:30
1   2024-02-18 12:55:45
2   2024-02-19 13:30:15
Name: DateTime4, dtype: datetime64[ns]

In [39]:
# 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      3 non-null      datetime64[ns]
 1   Date2      3 non-null      datetime64[ns]
 2   Date3      3 non-null      datetime64[ns]
 3   Date4      3 non-null      datetime64[ns]
 4   Date5      3 non-null      datetime64[ns]
 5   Date6      3 non-null      datetime64[ns]
 6   DateTime1  3 non-null      datetime64[ns]
 7   DateTime2  3 non-null      datetime64[ns]
 8   DateTime3  3 non-null      datetime64[ns]
 9   DateTime4  3 non-null      datetime64[ns]
dtypes: datetime64[ns](10)
memory usage: 368.0 bytes

In [40]:
# 년, 월, 일, 시간, 분, 초 추출
df['year'] = df['DateTime4'].dt.year
df['month'] = df['DateTime4'].dt.month
df['day'] = df['DateTime4'].dt.day
df['hour'] = df['DateTime4'].dt.hour
df['minute'] = df['DateTime4'].dt.minute
df['secend'] = df['DateTime4'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,secend
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024,2,17,11,45,30
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024,2,18,12,55,45
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024,2,19,13,30,15

In [ ]:
# 요일 dayofweek
# 0:월, 1:화, 2:수, 3:목, 4:금, 5:토, 6:일
df['DateTime4'].dt.dayofweek

0    5
1    6
2    0
Name: DateTime4, dtype: int32

In [45]:
# 주말
df['is주말'] = df['DateTime4'].dt.dayofweek >= 5
df

,Date1,Date2,Date3,Date4,Date5,Date6,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,secend,is주말
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024-02-17 11:45:30,2024,2,17,11,45,30,True
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024-02-18 12:55:45,2024,2,18,12,55,45,True
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024-02-19 13:30:15,2024,2,19,13,30,15,False

## 시계열 데이터 (Timedelta)
* 시점 계산

In [46]:
# 데이터 불러오기 (usecols, parse_dates)
# usecols = 어떤 특정 열만 쓰겠다.
# parse_dates = datetime으로 바꿈
df = pd.read_csv("date.csv", usecols = ['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 11:45:30
1 2024-02-18 12:55:45
2 2024-02-19 13:30:15

In [47]:
# 100일째 되는 날
day = pd.Timedelta(days=99)
df['100일'] = df['DateTime4'] + day
df

            DateTime4                100일
0 2024-02-17 11:45:30 2024-05-26 11:45:30
1 2024-02-18 12:55:45 2024-05-27 12:55:45
2 2024-02-19 13:30:15 2024-05-28 13:30:15

In [48]:
# 100시간 이후
hour = pd.Timedelta(hours=99)
df['100시간'] = df['DateTime4'] + hour
df

            DateTime4                100일               100시간
0 2024-02-17 11:45:30 2024-05-26 11:45:30 2024-02-21 14:45:30
1 2024-02-18 12:55:45 2024-05-27 12:55:45 2024-02-22 15:55:45
2 2024-02-19 13:30:15 2024-05-28 13:30:15 2024-02-23 16:30:15

In [49]:
# 시간 +/- (3주, 3일, 3시간, 3분 3초 이전과 이후)
diff = pd.Timedelta(weeks=3, days=3, hours=3,minutes=3,seconds=3)
df["+diff"] = df['DateTime4'] + diff
df["-diff"] = df['DateTime4'] - diff
df

,DateTime4,100일,100시간,+diff,-diff
0,2024-02-17 11:45:30,2024-05-26 11:45:30,2024-02-21 14:45:30,2024-03-12 14:48:33,2024-01-24 08:42:27
1,2024-02-18 12:55:45,2024-05-27 12:55:45,2024-02-22 15:55:45,2024-03-13 15:58:48,2024-01-25 09:52:42
2,2024-02-19 13:30:15,2024-05-28 13:30:15,2024-02-23 16:30:15,2024-03-14 16:33:18,2024-01-26 10:27:12

In [51]:
# timedelta 자료형(datetime간의 연산 결과)
diff = df['100일'] - df['100시간']
diff

0   94 days 21:00:00
1   94 days 21:00:00
2   94 days 21:00:00
dtype: timedelta64[ns]

In [54]:
# 기간을 초로 변환 total_seconds()
print(diff.dt.total_seconds()) # 초
print(diff.dt.total_seconds()/60) # 분
print(diff.dt.total_seconds()/60/60) # 시간
print(diff.dt.total_seconds()/60/60/24) # 일

0    8197200.0
1    8197200.0
2    8197200.0
dtype: float64
0    136620.0
1    136620.0
2    136620.0
dtype: float64
0    2277.0
1    2277.0
2    2277.0
dtype: float64
0    94.875
1    94.875
2    94.875
dtype: float64

In [56]:
# 일(days), 초(seconds)
print(diff.dt.days)
print(diff.dt.seconds) #94일은 제외하고 뒤에꺼만 차이 계산

0    94
1    94
2    94
dtype: int64
0    75600
1    75600
2    75600
dtype: int32

In [57]:
# 반올림(ex: 5.49분) 30초 이상이면 올림, 미만이면 버림
value = 5.49
round(value)

5