## Section1. 데이터프레임과 시리즈

In [30]:
import pandas as pd
# Series도 표로 렌더링되게 만들기
pd.Series._repr_html_ = lambda self: self.to_frame()._repr_html_()

In [31]:
# 시리즈 만들기
menu = pd.Series(['비빔밥','김치찌개','된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [32]:
# 시리즈 만들기
price = pd.Series([10000,9000,8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [33]:
# 데이터 프레임 만들기
pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [34]:
df = pd.DataFrame({
    "메뉴" : ['비빔밥', '김치찌개','된장찌개'],
    "가격" : [10000,9000,8000],
    "원산지" : ["국내산","국내산","국내산"]
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [35]:
# 시리즈 선택
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [36]:
# 데이터 프레임으로 선택하는 것 [[]]
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [37]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [38]:
# 데이터프레임 선택(메뉴, 가격)
cols = ['메뉴', '가격']
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [40]:
print("df            :",type(df))
print("df            :",type(df['가격']))
print("df            :",type(df[['가격']]))

df            : <class 'pandas.core.frame.DataFrame'>
df            : <class 'pandas.core.series.Series'>
df            : <class 'pandas.core.frame.DataFrame'>

## Section2. 데이터 저장 및 불러오기

In [42]:
# 데이터 준비하기
df = pd.DataFrame({
    "메뉴" : ["아메리카노","카페라떼","카페모카","카푸치노","에스프레소","밀크티","녹차"],
    "가격" : [4500,5000,5500,5000,4000,5900,5300],
    "칼로리" : [10,110,250,110,20,210,0]
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [43]:
# 데이터 저장하기
df.to_csv('temp.csv')

In [48]:
'''
저장할때 to_csv할떄 옵션을 안줘서 앞에있는 index값을 자동으로 저장
'''
temp_df = pd.read_csv('temp.csv')
temp_df.head() # 5개의 샘플만확인

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [49]:
# 데이터 불러오기
df.to_csv('cafe.csv', index=False)
df = pd.read_csv('cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

## Section3. 탐색적 데이터 분석(EDA)

In [50]:
# 데이터 샘플 확인 : 앞에서 부터 n개(기본 5개)
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [51]:
# 데이터 샘플 확인 : 뒤에서부터 n개(기본 5개)
df.tail(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [53]:
# 랜덤하게 샘플 출력
df.sample(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
5    밀크티  5900  210
2   카페모카  5500  250

In [56]:
# 데이터 프레임 크기(행, 컬럼)
df.shape

(7, 3)

In [57]:
# 컬럼 형태(type)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes

<code>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12372\3439580613.py in <module>
      1 # 상관관계
----> 2 df.corr()

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\frame.py in corr(self, method, min_periods, numeric_only)
  11074         cols = data.columns
  11075         idx = cols.copy()
> 11076         mat = data.to_numpy(dtype=float, na_value=np.nan, copy=False)
  11077 
  11078         if method == "pearson":

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\frame.py in to_numpy(self, dtype, copy, na_value)
   2000         if dtype is not None:
   2001             dtype = np.dtype(dtype)
-> 2002         result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
   2003         if result.dtype is not dtype:
   2004             result = np.asarray(result, dtype=dtype)

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\internals\managers.py in as_array(self, dtype, copy, na_value)
   1711                 arr.flags.writeable = False
   1712         else:
-> 1713             arr = self._interleave(dtype=dtype, na_value=na_value)
   1714             # The underlying data was copied within _interleave, so no need
...
-> 1772             result[rl.indexer] = arr
   1773             itemmask[rl.indexer] = 1
   1774 

ValueError: could not convert string to float: '아메리카노'
</code>

In [61]:
# 상관관계
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [63]:
# 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car" : ["Sedan","SUV","Sedan","SUV","SUV","SUV","Sedan","Sedan","Sedan","Sedan","Sedan"],
    "size" : ["S","M","S","S","M","M","L","S","S","M","S"]
})

In [64]:
df_car.head()

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S
3    SUV    S
4    SUV    M

In [65]:
# 항목 종류 수
df_car.nunique()

car     2
size    3
dtype: int64

In [66]:
# 항목 종류
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [68]:
# 항목별 개수
print(df_car['car'].value_counts())
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [70]:
df.describe() # 숫자형데이터만 보여줌

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [72]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [73]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1