## Section16. 그룹핑

In [3]:
import pandas as pd
df = pd.read_csv("cafe4.csv")
df

        메뉴    가격  칼로리    원산지    이벤트가
0    아메리카노  4500   10   콜롬비아     NaN
1     카페라떼  5000  110  코스타리카  1000.0
2     카페모카  5500  250  코스타리카  1000.0
3     카푸치노  5000  110  코스타리카     NaN
4    에스프레소  4000   20  코스타리카     NaN
5      밀크티  5900  210  코스타리카     NaN
6       녹차  5300    0   대한민국     NaN
7  크리스마스라떼  6000  300     한국     NaN

In [5]:
# 원산지 기준, 평균
df.groupby(['원산지']).mean(numeric_only=True)

           가격    칼로리    이벤트가
원산지
대한민국   5300.0    0.0     NaN
코스타리카  5080.0  140.0  1000.0
콜롬비아   4500.0   10.0     NaN
한국     6000.0  300.0     NaN

In [6]:
# 원산지와 칼로리 기준, 평균
df.groupby(['원산지','칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
대한민국  0    5300.0     NaN
코스타리카 20   4000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
      250  5500.0  1000.0
콜롬비아  10   4500.0     NaN
한국    300  6000.0     NaN

In [7]:
# 원산지와 메뉴 기준(평균,합계)
df.groupby(['원산지','메뉴']).agg(['mean','sum'])

                   가격          칼로리         이벤트가
                 mean   sum   mean  sum    mean     sum
원산지   메뉴
대한민국  녹차       5300.0  5300    0.0    0     NaN     0.0
코스타리카 밀크티      5900.0  5900  210.0  210     NaN     0.0
      에스프레소    4000.0  4000   20.0   20     NaN     0.0
      카페라떼     5000.0  5000  110.0  110  1000.0  1000.0
      카페모카     5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노     5000.0  5000  110.0  110     NaN     0.0
콜롬비아  아메리카노    4500.0  4500   10.0   10     NaN     0.0
한국    크리스마스라떼  6000.0  6000  300.0  300     NaN     0.0

In [8]:
# 1개 인덱스 형태로 리셋
df.groupby(['원산지','메뉴']).agg(['mean','sum']).reset_index()

     원산지       메뉴      가격          칼로리         이벤트가
                     mean   sum   mean  sum    mean     sum
0   대한민국       녹차  5300.0  5300    0.0    0     NaN     0.0
1  코스타리카      밀크티  5900.0  5900  210.0  210     NaN     0.0
2  코스타리카    에스프레소  4000.0  4000   20.0   20     NaN     0.0
3  코스타리카     카페라떼  5000.0  5000  110.0  110  1000.0  1000.0
4  코스타리카     카페모카  5500.0  5500  250.0  250  1000.0  1000.0
5  코스타리카     카푸치노  5000.0  5000  110.0  110     NaN     0.0
6   콜롬비아    아메리카노  4500.0  4500   10.0   10     NaN     0.0
7     한국  크리스마스라떼  6000.0  6000  300.0  300     NaN     0.0

In [9]:
# transform
import pandas as pd

# 데이터 생성 (일부 결측값 포함)
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [11]:
price = df.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [12]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [13]:
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '등급': ['B', 'B', 'A', 'A', 'A', 'A', 'B', 'B'],   # 새로운 그룹 추가
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [14]:
price = df.groupby(['과일','등급'])['가격'].transform("mean")
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [15]:
# unstack
import pandas as pd

coffee_data = {
    '커피종류': ['아메리카노', '아메리카노', '아메리카노', '라떼', '라떼', '라떼'],
    '컵크기': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large'],
    '판매량': [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [17]:
# groupby
g = df.groupby(['커피종류','컵크기'])['판매량'].sum()
g

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [18]:
# 컵크기를 컬럼으로 변환
g.unstack()

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [19]:
# 커피종류를 컬럼으로 변환
g.unstack(0)

커피종류     라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120

In [21]:
# 두 번의 unstack 적용
g.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

## Section19. 데이터 합치기

In [22]:
import pandas as pd

# 에피타이저 메뉴
appetizer = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Bread'],
    'Price': [5000, 3000, 2000]
})

# 메인 메뉴
main = pd.DataFrame({
    'Menu': ['Steak', 'Pasta', 'Chicken'],
    'Price': [15000, 12000, 10000]
})

print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [23]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer,main])
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [25]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer,main],ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [26]:
# 두 메뉴를 좌우로 연결
full_menu = pd.concat([appetizer,main], axis = 1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [27]:
# 메뉴와 가격
price = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Steak', 'Pasta'],
    'Price': [5000, 3000, 15000, 12000]
})

# 메뉴와 칼로리
cal = pd.DataFrame({
    'Menu': ['Soup', 'Steak', 'Pasta', 'Salad'],
    'Calories': [100, 500, 700, 150]
})

# 두 데이터프레임을 'Menu'를 기준으로 병합
menu_info = pd.merge(price, cal, on='Menu')
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       700

## Section 20. 피벗테이블

In [28]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서별 평균 급여 계산
pt = df.pivot_table(index='부서', values='급여', aggfunc='mean')
print("\n[부서별 평균 급여]")  #\n은 줄 바꿈(새로운 줄 시작)
print(pt)

[원본 데이터]
   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

[부서별 평균 급여]
        급여
부서
개발  3000.0
기획  3200.0

In [31]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '개발', '개발', '기획', '개발', '기획'],
    '직급': ['대리','과장','대리','과장','대리','과장'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 직급별 급여 합계 계산
pt = df.pivot_table(index='부서', columns = '직급', values='급여', aggfunc='sum')
print("\n[부서 및 직급별 급여 합계]")  #\n은 줄 바꿈(새로운 줄 시작)
print(pt)

[원본 데이터]
   이름  부서  직급    급여
0  서아  개발  대리  3000
1  다인  개발  과장  3200
2  채아  개발  대리  3100
3  예담  기획  과장  3300
4  종현  개발  대리  2900
5  태헌  기획  과장  3100

[부서 및 직급별 급여 합계]
직급      과장      대리
부서
개발  3200.0  9000.0
기획  6400.0     NaN

In [32]:
# 다양한 집계를 위한 데이터셋
import pandas as pd

df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
print(df)

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [33]:
pt = df.pivot_table(
    index = ['구분','유형'],
    columns = '크기',
    values='수량',
    aggfunc='sum'
)
pt

크기      대형   소형
구분 유형
가전 일반  4.0  5.0
   특수  7.0  6.0
전자 일반  4.0  1.0
   특수  NaN  6.0

In [34]:
pt = df.pivot_table(
    index = ['구분','유형'],
    columns = '크기',
    values='수량',
    aggfunc='sum',
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6