## Section4. 자료형 변환

In [3]:
import pandas as pd
# 데이터 준비
data = {
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리":['10', '110', '250', '110', '20', '210', '0'],
}

In [4]:
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 296.0+ bytes

In [6]:
# 자료형 변환 / astype / float -> int
df['가격'] = df['가격'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int32
 2   칼로리     7 non-null      object
dtypes: int32(1), object(2)
memory usage: 268.0+ bytes

In [7]:
# 자료형 변환 / astype / object -> float
df['칼로리'] = df['칼로리'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int32
 2   칼로리     7 non-null      int32
dtypes: int32(2), object(1)
memory usage: 240.0+ bytes

## Section5. 새로운 컬럼 추가

In [8]:
df = pd.read_csv('cafe.csv')

In [9]:
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [10]:
# 새로운 컬럼 추가(값은 0)
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [11]:
# 할인가 컬럼 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df.head(2)

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0

## Section6. 데이터 삭제(칼럼, 행)

In [12]:
# 행 삭제
# axis = 0 ==> 행을 선택하겠다.
df = df.drop(1, axis=0)
df.head(3)

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0

In [13]:
# 칼럼 삭제
# axis = 1 : 열방향삭제
df = df.drop('칼로리',axis=1)
df.head(3)

      메뉴    가격  new     할인가
0  아메리카노  4500    0  3600.0
2   카페모카  5500    0  4400.0
3   카푸치노  5000    0  4000.0

## Section7. 인덱싱/슬라이싱

In [17]:
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [16]:
# 인덱싱 (행 전체)
# 아메리카노
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [20]:
# 카페라테 가격
df.loc[1,"가격"]

5000

In [21]:
# 슬라이싱 (컬럼 전체)
# 가격
df.loc[:,"가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [22]:
# 슬라이싱
# 카페모카 메뉴와 칼로리
df.loc[2, ['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [23]:
# 슬라이싱
df.loc[1:3,'메뉴':'가격']

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

## Section8. 인덱싱/슬라이싱(iloc)
* 인덱스 번호
* 범위로 지정함

In [24]:
df = pd.read_csv('cafe.csv')
df = df.drop(0,axis=0)

In [25]:
df.head(2)

     메뉴    가격  칼로리
1  카페라떼  5000  110
2  카페모카  5500  250

In [26]:
# 인덱싱 (행 전체)
# 카페라떼
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [27]:
# 가격만 출력
df.iloc[:,1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [31]:
df

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [30]:
# 카푸치노 메뉴와 가격
df.iloc[2,0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [34]:
# 슬라이싱(카페모카와 카푸치노의 전체 데이터)
df.iloc[1:3]

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [35]:
df.loc[2:3,'메뉴':'칼로리']

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110